### ISSUE TITLE
Invalid sha1sum in hunter.cmake for yaml-cpp

### ISSUE THREAD

**Issue by harsszegi** [ruslo/hunter#1055]
For some reason the SHA1 hash of the release-0.5.3-hunter-p2.tar.gz package on github has changed from ee1fe3713409de48b203f6b631c1284190d95671 to da0f41b63be987b468e3a45c1d449ba18cc502d3. Please either restore the original .tar.gz or update the sha1sum in hunter.cmake

**Comment by ruslo** [comment]
See details here:
* https://github.com/ruslo/hunter/issues/1032#issuecomment-329382772

As a solution if you have archive with sources locally (in `~/.hunter/_Base/Downloads`) please upload it and we will change URL without changing SHA1. Otherwise add new SHA1, but note that this will affect binary cache and we have to re-upload libraries.

**Comment by harsszegi** [comment]
Oops, where should I upload the "original" matching the SHA1? (sorry lame me)

**Comment by ruslo** [comment]
> Where should I upload the "original" matching the SHA1?

Anywhere, I will download it, check and upload as asset to https://github.com/hunter-packages/yaml-cpp/releases/tag/release-0.5.3-hunter-p2

**Comment by harsszegi** [comment]
https://filebin.ca/3b1pACirHU6P/release-0.5.3-hunter-p2.tar.gz
Thanks in advance!

**Comment by ruslo** [comment]
Fixed: https://github.com/ruslo/hunter/releases/tag/v0.19.108
