### ISSUE TITLE
Updating to v0.19.115 -> cannot find -lglog & -lgflags-static

### ISSUE THREAD

**Issue by ibayer** [ruslo/hunter#1068]
Hi,

I have upgraded my hunter to adapt to the new SHA1 keys.

``` diff
 HunterGate(
-    URL "https://github.com/ruslo/hunter/archive/v0.17.5.tar.gz"
-    SHA1 "033a6ff2cd804144ad55a990bcd631a838ab5d32"
+    URL "https://github.com/ruslo/hunter/archive/v0.19.115.tar.gz"
+    SHA1 "aeb37c4b667c4201837bcac38702f3ce8b4a9b44"
     LOCAL
 )

```

Somehow this lead to issues in the formally working build process.

```
Linking CXX executable IFM_proto

/usr/bin/cmake -E cmake_link_script CMakeFiles/IFM_proto.dir/link.txt --verbose=1

/usr/bin/g++    -std=c++11 -O3 -DNDEBUG   CMakeFiles/IFM_proto.dir/ifm_proto.cpp.o  -o IFM_proto -rdynamic fastFM/libfastFM.a fastFM_app/libfastFM-app.a -lgflags-static -ldl -lglog /home/travis/.hunter/_Base/aeb37c4/266cf4a/8913be5/Install/lib/libprotobuf.a -lpthread /home/travis/.hunter/_Base/aeb37c4/266cf4a/8913be5/Install/lib/libz.a 

/usr/bin/ld: cannot find -lgflags-static

/usr/bin/ld: cannot find -lglog

collect2: error: ld returned 1 exit status

make[2]: *** [IFM_proto] Error 1

make[2]: Leaving directory `/home/travis/build/ibayer/fastFM-core2/_builds'

make[1]: *** [CMakeFiles/IFM_proto.dir/all] Error 2

make[1]: Leaving directory `/home/travis/build/ibayer/fastFM-core2/_builds'

make: *** [all] Error 2

```

Any idea which change could have caused this?

**Comment by ruslo** [comment]
> /usr/bin/ld: cannot find -lglog

Name of the imported target changed from `glog` to `glog::glog`. Targets without "namespace" like `glog::` treated as regular libraries by CMake. If there is no `glog` target then `-lglog` will be used while linking. Also this is the reason why this change introduced: if there will be no `glog::glog` imported target then CMake will report error on configure step instead of linking step:
* https://docs.hunter.sh/en/latest/packages/pkg/glog.html

> /usr/bin/ld: cannot find -lgflags-static

Same reason `gflags-static` changed to `gflags`:
* https://docs.hunter.sh/en/latest/packages/pkg/gflags.html

Static/shared build should be controlled by `CMAKE_ARGS BUILD_SHARED_LIBS=ON` and not by target name.

Fixed: https://github.com/ibayer/fastFM-core2/pull/44

**Comment by ibayer** [comment]
@ruslo 
Thanks for pointing to the change explaining the reason for it.
