### ISSUE TITLE
libxml2 on Visual Studio 2017, Win 10, CMake 3.10.0-rc4

### ISSUE THREAD

**Issue by richardeigenmann** [ruslo/hunter#1173]
Trying to prove that C++ is cross platform I came across Hunter which looks really impressive!

I'm trying to compile a simple program that uses Curl, Boost and libxml2.

For libxml2 I have the following minimalist CMakeLists.txt:

cmake_minimum_required(VERSION 3.0)
include("HunterGate.cmake")
HunterGate(
	URL "https://github.com/ruslo/hunter/archive/v0.19.144.tar.gz"
	SHA1 "e3efd470f8b60468db8730eac8c04792f77fe1b1"
)
project(foo)
hunter_add_package( libxml2 )
add_executable(foo foo.cpp)

on the cmd I run various permutations of:
cmake -H. -B_builds -G"Visual Studio 15 2017 Win64" -DHUNTER_STATUS_DEBUG=ON -DHUNTER_CONFIGURATION_TYPES=Release

But I end up with:
[hunter ** FATAL ERROR **] Autotools scheme not supported with Visual Studio

How do I overcome this? The readme on this site gives me the impression that the library should be buildable with Visual Studio: https://github.com/winlibs/libxml2/tree/master/win32

**Comment by headupinclouds** [comment]
> Autotools scheme not supported with Visual Studio.  How do I overcome this?

Hunter is implemented in CMake, and it typically works best with CMake packages.  However, many libraries rely on the autotools build system.  For these cases, hunter maintains an autotools *scheme* (via a CMake "binding") to support such libraries out of the box.  That will limit those packages to platforms that support autotools.  To add portability, such packages are often forked to `hunter-packages` where a portable `CMakeLists.txt` file can be added (and ideally submitted upstream).

You can often track down a CMakeLists.txt on github with a quick search.  Here is an example I found  for libxml2: https://github.com/martell/libxml2.cmake/blob/master/CmakeLists.txt.  This is probably very close to what is needed, but a package configuration file needs to be added and installed so that `hunter_add_package(libxml2) find_package(libxml2 CONFIG REQUIRED)` will work smoothly.  I use this project as boilerplate for creating the necessary installation steps:

https://github.com/forexample/package-example

See : https://github.com/forexample/package-example/blob/master/Foo/CMakeLists.txt

**Comment by headupinclouds** [comment]
BTW, here is the hunter package specification: https://github.com/ruslo/hunter/blob/master/cmake/projects/libxml2/hunter.cmake

The package is using the upstream tagged release, so the `url_sha1_autotools` scheme is used:

https://github.com/ruslo/hunter/blob/0dc4bb5f608e6a72861a7d5812c3b7e9230ff97c/cmake/projects/libxml2/hunter.cmake#L32
```
hunter_pick_scheme(DEFAULT url_sha1_autotools)
```

If you create an issue with the subject `add libxml2 to hunter-packages`, a fork will be created, and you can patch it with a CMakeLists.txt file and submit a PR for the CMake version.

**Comment by richardeigenmann** [comment]
Thank you for your helpful comments. I have created the issue as you suggest. I will now also raise an issue for libiconv as we will need that too for libxml2.

**Comment by headupinclouds** [comment]
From gittter: https://gitter.im/ruslo/hunter?at=59f99c335a1758ed0f759c70

FYI, @ruslo (hunter author) mentioned he'll be away through the 9th.

**Comment by xsacha** [comment]
The problem is it is not trivial to convert autotools projects to CMake.
Also, I would say these packages are 'cross-platform' but just not 'cross-compiler'. Sometimes you need to use MinGW on that platform rather than Visual Studio. Or, if your compiler of choice is not supported for certain packages sometimes the best idea is to have that package pre-built.

**Comment by xsacha** [comment]
Working on Visual Studio 2017, Win 10, CMake 3.10.0-rc4 via #1262

**Comment by ruslo** [comment]
Closing inactive discussion.
