### ISSUE TITLE
fork cryptopp

### ISSUE THREAD

**Issue by dmakarov** [ruslo/hunter#1198]
need to patch https://github.com/weidai11/cryptopp to make it build when Xcode generator is used.

**Comment by ruslo** [comment]
Done: https://github.com/hunter-packages/cryptopp

Looks like they removed CMake support because no one was capable to maintain it:
* https://www.cryptopp.com/wiki/CMake#CMake_Removal

@dmakarov I've invited you to the team. After you accept invitation (check your email) you will have write access. Please read this before:
* https://docs.hunter.sh/en/latest/creating-new/patch.html

**Comment by dmakarov** [comment]
Thanks! All the more important to have a fork that includes cmake support.

**Comment by ruslo** [comment]
Closing inactive discussion.
