### ISSUE TITLE
Naming of Boost unit test framework

### ISSUE THREAD

**Issue by CHChang810716** [ruslo/hunter#1238]
I think this should be a bug.

The problem is I can add boost test package by:
``` hunter_add_package( Boost COMPONENTS test ) ```

But I can't find the package by:
``` find_package(Boost CONFIG COMPONENTS test ) ```

I have to find the package by
``` find_package(Boost CONFIG COMPONENTS unit_test_framework ) ``` .

And I can't link target by:
``` target_link_libraries(foo Boost::test ) ```

Is this the correct behavior of Boost package ?

**Comment by ruslo** [comment]
> The problem is I can add boost test package by
> hunter_add_package( Boost COMPONENTS test )

Boost build use `--with-<COMPONENT>`, it have to be `b2 --with-test`:
* https://github.com/ruslo/hunter/blob/c4491353ebef3a57b4165dacc66f42db7cac2df5/cmake/projects/Boost/schemes/url_sha1_boost_library.cmake.in#L219-L229

> But I can't find the package by:
> find_package(Boost CONFIG COMPONENTS test )

This is because standard `FindBoost.cmake` use `unit_test_framework`:
* https://cmake.org/cmake/help/latest/module/FindBoost.html
* https://stackoverflow.com/questions/9881288/compiling-a-boost-test-with-cmake#9881783

> Is this the correct behavior of Boost package ?

Yes, see example:
* https://github.com/ruslo/hunter/blob/c4491353ebef3a57b4165dacc66f42db7cac2df5/examples/Boost-test/CMakeLists.txt#L12-L13

**Comment by CHChang810716** [comment]
OK, I got it.
Thanks!
