### ISSUE TITLE
Updating flatbuffers to 1.8.0: case issue

### ISSUE THREAD

**Issue by Meoo** [ruslo/hunter#1239]
I am porting flatbuffers 1.8.0 to hunter, but I'm getting a case issue in linux.
Upstream is using "Flatbuffers" while hunter's current version is using "flatbuffers"
This cause an error on linux where files are case sensitive

Using the capital in projects fix the issue:
```
hunter_add_package(flatbuffers)
find_package(Flatbuffers CONFIG REQUIRED)
             ^
```
But this will break backward compatibility for current verison.

Should I just remove the previous version and rename hunter package to "Flatbuffers"?

Used flatbuf's commit:
* https://github.com/google/flatbuffers/tree/ba08b0ec0266f505bfe06e49e993091157e19c93

CI tests:
* https://ci.appveyor.com/project/Meoo/hunter/build/15
  * mingw fails because M_PI is not standard (I'll open an issue for that)
  * Otherwise, all green
* https://travis-ci.org/Meoo/hunter/builds/310195737
  * OSX seems to work fine
  * Every linux build can't find `flatbuffersConfig.cmake`, `FlatbuffersConfig.cmake` is present

**Comment by ruslo** [comment]
> Upstream is using "Flatbuffers" while hunter's current version is using "flatbuffers"

Upstream version was not working from the box, Hunter use patched version:
* https://github.com/ruslo/hunter/blob/c4491353ebef3a57b4165dacc66f42db7cac2df5/cmake/projects/flatbuffers/hunter.cmake#L12-L21

If new upstream version work from the box then let's use their filenames, i.e. let it be `find_package(Flatbuffers ...)` instead of `find_package(flatbuffers ...)`. Just mention it in documentation.

**Comment by Meoo** [comment]
Alright I changed the name and added comments in documentation

PR https://github.com/ruslo/hunter/pull/1241
