### ISSUE TITLE
Android Boost Threads compiled on Windows error

### ISSUE THREAD

**Issue by xsacha** [ruslo/hunter#1310]
When cross-compiling Boost Thread for Android on Windows, I get the following error:
[ 75%] Performing build step for 'Boost-thread'
'cygpath' is not recognized as an internal or external command,

Is cygpath now a required binary in PATH for cross-compiling on Windows or should this be resolved somehow by modifying the .jam file?

**Comment by xsacha** [comment]
After overcoming this issue (by adding cygpath to PATH), I get this on ARM 32-bit (armeabi-v7a):

error: Name clash for '<pstage\lib>libboost_system-mt-d.a'
error:
error: Tried to build the target twice, with property sets having
error: these incompatible properties:
error:
error:     -  <address-model>32
error:     -  <address-model>64
error:
error: Please make sure to have consistent requirements for these
error: properties everywhere in your project, especially for install
error: targets.


Looks like the issue that was happening on Windows 32-bit.

**Comment by ruslo** [comment]
> Is cygpath now a required binary in PATH for cross-compiling on Windows or should this be resolved somehow by modifying the .jam file?

I haven't used Android build on Windows host, can't say anything.

**Comment by xsacha** [comment]
Found a fix in #1355

**Comment by gkontsevich** [comment]
> After overcoming this issue (by adding cygpath to PATH),

Where did you find cygpath @xsacha ? Did you install Cygwin (which is GPL and a bit scary.. but maybe okay b/c it's just to run Make and other tools)?

I'm not quite sure how to setup the config/build, so any tips would be appreciated :)

I'm trying to get an Android build going in Windows and am a bit stuck. The NDK provides the toolchain/compiler/etc. (though I wrote my own very short toolchainfile) but I'm not even quite which generator to use. I assume VS won't work, so I'm making a little progress with MinGW (which is on my system thanks to git). 

As I understand it, I need MinGW basically just to run make which will in turn run the actual toolchains in the NDK.. and now maybe Cygwin? Is that right?

**Comment by ruslo** [comment]
> I'm not quite sure how to setup the config/build, so any tips would be appreciated :)

I think Android Studio should work: https://docs.hunter.sh/en/latest/faq/android-studio.html But few steps are tricky there for different reasons, please read it carefully and try simple example without Boost first.

**Comment by ruslo** [comment]
Android toolchains from Polly are working fine on Linux/macOS: https://github.com/ruslo/polly

**Comment by gkontsevich** [comment]
Thanks for the links @ruslo !! Looks like things are moving fast :)

My team has so far been building an NDK based lib separately on Linux and then copying it over in to AS on Windows (b/c that's what the Android guys are using). It's a bit clunky, but I do have the whole Linux/NDK side building with Hunter thanks to your work - so a big thank you! The whole build system is so much more robust thanks to Hunter. I did end up having some issues with polly's android toolchain files and ended up just putting a small toolchain file in the NDK directory 

``` cmake
set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_ANDROID_ARCH_ABI armeabi-v7a)
set(CMAKE_ANDROID_ARM_NEON ON)
set(CMAKE_ANDROID_NDK ${CMAKE_CURRENT_LIST_DIR})  #/path/to/android-ndk)
set(CMAKE_ANDROID_STL_TYPE gnustl_static)

set (CMAKE_CXX_STANDARD 11)
```

Let me know if this is a dangerous mistake :) I've been using polly otherwise for desktop builds on both Windows and Linux without any issues. It's a very convenient tool

But ultimately ofcourse it'd be best if the Android build could also be done on Windows directly so I will definitely look more into this Android Studio integration. It seems the instructions are for Android Studio on Linux, have you got it running on Windows as well? And do the android toolchain files in Polly work for both systems?

**Comment by ruslo** [comment]
> Let me know if this is a dangerous mistake :) I've been using polly otherwise for desktop builds on both Windows and Linux without any issues. It's a very convenient tool

Toolchain looks fine.

> But ultimately ofcourse it'd be best if the Android build could also be done on Windows directly

Have you tried Ninja generator instead of Makefile?

> have you got it running on Windows as well?

I have checked it once, but not using it regularly.

> And do the android toolchain files in Polly work for both systems?

Android toolchains require Makefile generator, I have never tried to make in work on Windows.

**Comment by ruslo** [comment]
> reusing the AndroidStudio internal toolchain/configuration and I won't need Polly in that case

Yes, Polly will not be used in Android Studio setup.
