### ISSUE TITLE
gRPC build MC 2015 error ZLIB::zlib

### ISSUE THREAD

**Issue by xelavoprak** [ruslo/hunter#1327]
From examples:
[CMakeLists.txt](https://github.com/ruslo/hunter/files/1666897/CMakeLists.txt)

cmake/HUNTER/config.cmake :
hunter_config(ZLIB VERSION ${HUNTER_ZLIB_VERSION} CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=TRUE )

cmake.exe -H. -B_build -DHUNTER_STATUS_DEBUG=ON -DHUNTER_CONFIGURATION_TYPES=Release -DCMAKE_TOOLCHAIN_FILE=C:/git/polly/vs-14-2015.cmake -G "Visual Studio 14 2015" -DCMAKE_VERBOSE_MAKEFILE=ON
have errors, out:
[hunter_log.txt](https://github.com/ruslo/hunter/files/1666905/hunter_log.txt)

If set hunter_add_package(ZLIB) before hunter_add_package(gRPC), clear cmake/HUNTER/config.cmake and find_package(ZLIB CONFIG REQUIRED) before find_package(gRPC CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME} gRPC::grpc)
build success, but not testing)

**Comment by ruslo** [comment]
```
CMake Error at CMakeLists.txt:36 (add_executable):
  Target "simple" links to target "ZLIB::zlib" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
```

I guess `hunter_add_package(ZLIB)` or/and `find_package(ZLIB CONFIG REQUIRED)` is missing.

> If set ...

Please post one question/example at a time. Can you show an example where you have error `Target "simple" links to target "ZLIB::zlib" but the target was not found`?

**Comment by xelavoprak** [comment]
`git clone https://github.com/ruslo/hunter`
`cd hunter/examples/gRPC/`
`cmake.exe -H. -B_build -DHUNTER_STATUS_DEBUG=ON -DHUNTER_CONFIGURATION_TYPES=Release -DCMAKE_TOOLCHAIN_FILE=C:/git/polly/vs-14-2015.cmake -G "Visual Studio 14 2015" -DCMAKE_VERBOSE_MAKEFILE=ON`
out:
`CMake Error at CMakeLists.txt:36 (add_executable):
  Target "simple" links to target "ZLIB::zlib" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?`

**Comment by ruslo** [comment]
That's because gRPC depends on ZLIB:
* https://github.com/hunter-packages/grpc/blob/5a5def5f5edd360cb000e91bf917d75c02abf6cf/CMakeLists.txt#L133-L135

But call to `find_package(ZLIB CONFIG REQUIRED)` is missing in generated `gRPCConfig.cmake`.

Looks like macro was not expanded properly:
* https://github.com/hunter-packages/grpc/blob/5a5def5f5edd360cb000e91bf917d75c02abf6cf/cmake/gRPCConfig.cmake.in#L2

Note: gRPC is not regularly tested on Windows, all toolchains excluded:
* https://github.com/ingenue/hunter/blob/7922436239173b9c1f3a4e9ef4c19ccca8c46eb0/appveyor.yml#L15-L45

**Comment by ruslo** [comment]
Closing inactive issue with "Broken package" label, see details:
* https://github.com/ruslo/hunter/wiki/error.external.build.failed
