### ISSUE TITLE
Add imgui package

### ISSUE THREAD

**Issue by NukeBird** [ruslo/hunter#1520]
* I'm interested in package `imgui`
* Here is official site of package https://github.com/ocornut/imgui
* This package is using Git: https://github.com/ocornut/imgui.git
* Official GitHub repository: https://github.com/ocornut/imgui
* Used build system: custom (?)
* This package has no external dependencies

**Comment by NukeBird** [comment]
seems like all we need to do is just copy this files:

> imgui.cpp
> imgui.h
> imgui_demo.cpp
> imgui_draw.cpp
> imgui_internal.h
> imconfig.h (empty by default, user-editable)
> stb_rect_pack.h
> stb_textedit.h
> stb_truetype.h

(list from official README)

**Comment by OvermindDL1** [comment]
Not copy, link them in rather, and imconfig.h will need to be generated from user-specified options in the cmake scripts to be done right I'd think.

**Comment by NukeBird** [comment]
@OvermindDL1 yes, it makes sense

So... Is there any chances to add imgui package to hunter?

**Comment by caseymcc** [comment]
Ill work on a package for this next week, may play with it this weekend but more likely next week. @ruslo can you create a hunter_packages/imgui for this, I will create a cmake file for it that will need a location. Ill see if the main repo wants in the end as well.

**Comment by NukeBird** [comment]
@caseymcc sounds great!

**Comment by caseymcc** [comment]
looks like I got it working,

https://travis-ci.org/caseymcc/hunter/builds/417903133
https://ci.appveyor.com/project/caseymcc/hunter/build/1.0.181

This one was a weird one, never setup a "library" to include cpp files into the project that is including it. Luckily cmake in 3.1 added support for this otherwise might have been a hack.

Once ruslo adds the hunter_package I can put in the PRs to get it into the main line.

**Comment by caseymcc** [comment]
@NukeBird package PR is in. Once test are completed and ruslo makes the next hunter release it should be good to go. Cheers!

**Comment by OvermindDL1** [comment]
It's also good to note that ocornut is receptive to CMakeList.txt additions and fixes to his main repo, so you might not need that secondary repo at all.  Only reason he doesn't is because he states that he doesn't know cmake, but if anyone else PR's it in and it seems to work then he will include it.

**Comment by caseymcc** [comment]
yeah, I put in a PR for it then found out they currently have a cmake PR in the works. Once they get it complete I will check it and make changes as needed then update the hunter package.

**Comment by OvermindDL1** [comment]
Oh hey, I remember that cmake conversation starting up there a long while ago, I thought it stalled, I hadn't kept up with it.  ^.^;

**Comment by NukeBird** [comment]
@caseymcc wow! Thank you so much! Can't wait when it will be released :3

**Comment by ruslo** [comment]
Fixed by https://github.com/ruslo/hunter/pull/1521
