### ISSUE TITLE
Possibility of 'extension' packages?

### ISSUE THREAD

**Issue by All8Up** [ruslo/hunter#1540]
I very much enjoy Hunter compared to managing a ton of 3rdParty items manually but there is one issue I have which revolves around licensed items which I can not integrate into hunter.  I would still like these items to work via hunter in order to have a single path to manage versions and binary caching etc.  Given this, I was wondering how difficult it would be to add something similar to the module path cmake uses but for hunter, i.e.:

`set (HUNTER_EXT_PACKAGE "${HUNTER_EXT_PACKAGE};${CMAKE_CURRENT_LIST_DIR}/PrivatePackages")`

In this manner I could manage the licensed items just like public packages with all the versioning, build setup etc in a uniform manner.  Given that these are optional plugins to support an open source codebase, the results could then be pushed as hunter binaries to the cache and I won't get dinged for breaking the license agreement.

This is not a huge issue since I can always just write config's manually using the normal approach but I would very much prefer to have the single method of integrating versioning and the other benefits of using hunterization.

**Comment by OvermindDL1** [comment]
I'm curious, why don't you just set up a private repo and then use both Hunter's public and your private repo together to get both public and your private dependencies?

**Comment by All8Up** [comment]
I'm not sure I understand what you mean.  The sources of the licensed items are in a private repo and that is what I would like to integrate into hunter.  But I can not release the integration code or the direct outputs of that repository (yes, I despise strict licenses like this one but it's what I have).  In the private source/public binary side I would like to use hunter to manage the versions of the private item, build and do all the normal hunter things, but only for this one project.   I have a couple related projects with different dependencies with similar licenses which prevent me from doing any public work with those items, though the end product plugins are fine to release.

**Comment by OvermindDL1** [comment]
Exactly, since you can't release it then make a private repo.  :-)

Basically you know this command from huntergate?

```cmake
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.16.15.tar.gz"
    SHA1 "6974c2150fc0d3b09de3ad1efcbf15d360647ffa"
)
```

Or whatever version you use, well right after it add a:

```cmake
HunterGate(
    URL "https://my_internal_server/my_repo_file/v0.1.4.tar.gz"
    SHA1 "BlahBlahBlahBlahBlahBlahBlahBlahBlahBlah"
)
```

I.E. you make your own private package repository with your own private listings that then acquire the internal dependency in a completely private way.  :-)

I do admit that Hunter needs more documentation on making personal repositories though, but it's not too hard...  Worst case is you can just merge your private code with a public hunter repo release then just use that locally.  :-)

**Comment by All8Up** [comment]
Ok, yes I had considered that and it is actually what I'll likely end up with.  It just makes things a maintenance hassle in a couple ways.  First, github doesn't allow a private fork from a public repo, so I have to futz around with setting up the remotes there.  Then of course the items which use those versions of hunter will have a separate maintenance path.
All said and done, this is all doable and not preventing anything, I just hope we could add something to better support these one off cases.  I just unfortunately have to deal with people whose licenses are stupid (cough $0ny, Nint3nbums, cough)..  :D

**Comment by OvermindDL1** [comment]
You don't actually need to fork hunter's packages, can just make your own with just your packages and then just use both repositories in your project.  :-)

**Comment by All8Up** [comment]
Ooooo, how do I use two repo's at the same time then?  *That* would solve the problem of having one out of date and the other coming from mainline.  I didn't think you could have multiple package sets given how sensitive the defaults file seems to be about ordering and such.

**Comment by OvermindDL1** [comment]
As far as I know, though not tried it, you just do two+ `HunterGate` calls?  I don't know which ordering, if any, takes precedence though.

**Comment by OvermindDL1** [comment]
You could try importing the stock package via two `HunterGate` calls twice to see what it does as a start?  I'm curious.  :-)

**Comment by All8Up** [comment]
So, gave this a try and it does seem to work.  Now I'm a bit curious where the docs for this would happen to be since I'd like to minimize what is in the private hunter.  I.e. removing all the other packages, what else can be removed etc?
Anyway, thank you greatly.  I think this will work quite well, definitely better than what I was trying to do.

**Comment by ruslo** [comment]
> there is one issue I have which revolves around licensed items which I can not integrate into hunter

@All8Up Packages can be injected into set by explicit URL/SHA1/VERSION without modifying Hunter archive, see:
* https://docs.hunter.sh/en/latest/reference/user-modules/hunter_config.html

I.e. you can do `hunter_config(foo URL "..." SHA1 "..." VERSION "...")`

> well right after it add a

@OvermindDL1 "right after" will not have any effect, only URL/SHA1 of first HunterGate will be used (the reason is that `Hunter-ID` directory should be ready/created after HunterGate call). In your example you should use `https://my_internal_server/my_repo_file/v0.1.4.tar.gz` **instead of** `https://github.com/ruslo/hunter/archive/v0.16.15.tar.gz`, **not** after.

**Comment by All8Up** [comment]
This answers a number of issues I had getting this working properly.  I will try the hunter_config variation as that seems a much more practical solution overall.
