### ISSUE TITLE
Question: using Find* scripts inside schemes to find libraries inside EP_BASE

### ISSUE THREAD

**Issue by pretyman** [ruslo/hunter#160]
Hi Ruslan,

I am compiling a library (odb-sqlite) autotools which depends on a previously compiled library with autotools (odb-core). However I am having trouble finding a portable manner to add the library directories created by `hunter-id/config-id/toolchain-id` inside the autotools scheme file. 

I was unable to pinpoint what CMake command/variable does hunter run/set so the `find_library`/`find_path` find things inside the `_Base/hunter-id/config-id/toolchain-id/Install` directory. When running the `find_package` from within the scheme file, nothing is found.

Seems like `@HUNTER_PACKAGE_INSTALL_PREFIX@` points to a temporary directory where the a tarball will be created and put into the Cache directory, and does not point to the final destination.

What do I need to set to have my `Find*` scripts which inside use `find_library` and `find_path` to find the library directory and include directory to search inside `_Base/hunter-id/config-id/toolchain-id/Install` directory?

Thanks

**Comment by ruslo** [comment]
> However I am having trouble finding a portable manner to add the library directories created by hunter-id/config-id/toolchain-id inside the autotools scheme file

This is package-specific. Unfortunatelly this is not unified in CMake world. You have to look at wiki page every time you want to add a package. Example:
* [OpenSSL](https://github.com/ruslo/hunter/wiki/pkg.openssl)
* [BZip2](https://github.com/ruslo/hunter/wiki/pkg.bzip2)

> I was unable to pinpoint what CMake command/variable does hunter run/set so the find_library/find_path find things inside the _Base/hunter-id/config-id/toolchain-id/Install directory

Every `hunter_add_package` command set `<package>_ROOT` variable (CMake, CMake cache and environment). E.g. `hunter_add_package(Foo)` will set `FOO_ROOT` variable. Expected that `Find*` modules from CMake use `FOO_ROOT` variable to find the libraries. But in fact there is no any guarantee. In case you need to have custom behaviour you can add your `FindFoo` script to [cmake/find](https://github.com/ruslo/hunter/tree/master/cmake/find) directory. This directory will be added to `CMAKE_MODULE_PATH` list and hence will have higher priority than CMake's standard `FindFoo`.

The situations is much better with `find_package(CONFIG)` packages. Since there is only need to modify `CMAKE_PREFIX_PATH` variable. This variable used by all packages.

> Seems like @HUNTER_PACKAGE_INSTALL_PREFIX@ points to a temporary directory where the a tarball will be created and put into the Cache directory, and does not point to the final destination

This is true only for [cacheable](https://github.com/ruslo/hunter/wiki/dev.modules#hunter_cacheable) packages. By default package is not cacheable.

> What do I need to set to have my Find* scripts which inside use find_library and find_path to find the library directory and include directory to search inside _Base/hunter-id/config-id/toolchain-id/Install directory?

It depends on what exactly you need. In short if `FindFoo` script do not respect `FOO_ROOT` you need to patch it and place to the `cmake/find` directory

**Comment by pretyman** [comment]
Thanks, your answer was very clarifying.

**Comment by pretyman** [comment]
Great, using setting FOO_ROOT in the url_sha1_schema with `set(FOO_ROOT "@FOO_ROOT@")` did the trick!
