### ISSUE TITLE
Simultaneous hunter builds?

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#163]
Are simultaneous hunter builds of the same (or different) project(s) using different toolchains supported?

**Comment by ruslo** [comment]
Any number of projects and/or toolchains can be started simultaneously.

Quote from [README](https://github.com/ruslo/hunter#features):
```
* Shareable root directory with build synchronization
 * Any number of projects can use root directory and add new packages simultaneously
```

Have you experienced any problems?

**Comment by headupinclouds** [comment]
Of course it was in the README ;)  I haven't tested this scenario yet.

**Comment by headupinclouds** [comment]
After confirmation of simultaneous build support I started testing this.  I'm pretty sure I hit a deadlock condition while building the same project for Android and OS X/Xcode.  I pulled the latest of everything from polly and hunter about an hour ago.

Attached is a screen shot showing the last build instruction from each terminal.

![hunter-deadlock](https://cloud.githubusercontent.com/assets/554720/8110675/9d377e08-102b-11e5-8873-3367c0826e36.png)

**Comment by headupinclouds** [comment]
UPDATE: This freeze may have nothing to do with simultaneous builds.  If I kill both and repeat the same OS X build it freezes in the same place.  I'll look into it further.
```
build.py --toolchain xcode --verbose --fwd HUNTER_CONFIGURATION_TYPES=Release --jobs 8 --open --clear
```

**Comment by ruslo** [comment]
From the screenshots I see that first build started with debug info (`HUNTER_STATUS_DEBUG=ON`) does debug info enabled for the second build? There is only one place where `file(LOCK ...)` used, it's `hunter_lock_directory` module. And before call to `file(LOCK ...)` there is message: `Locking directory: ...`. So when I've experienced synchronization issue before I have `Locking directory: ...` message in both consoles. For now I see no problems - since `Cache` shared between several instances it's quite normal situations when one instance wait for other even for different toolchain-id's. Note that saving to cache is the final stage of build so `android` and `osx` toolchains must builds simultaneously. May be it's just need some time to create an archive since OpenCV quite big?

>  I wonder if there is a way to unit test this on travis?

Well if you said that building from scratch does work it make no sense to test it on travis. As usual in programming world synchronizations problems are very annoying and not easy debuggable-testable. The only advice I have is to turn `HUNTER_STATUS_DEBUG=ON` for builds and save all the logs when you think you find deadlocks.

**Comment by headupinclouds** [comment]
I will try some more parallel builds in the future.  I was referring to a simultaneous build test in the above, but wasn't sure if that was possible on travis.  Possibly that would require a full fledged cloud instance.  I'll close this for now and reopen if I run into a problem again.
