### ISSUE TITLE
OpenCV's Extra Modules

### ISSUE THREAD

**Issue by ahundt** [ruslo/hunter#167]
Is it possible to also support [OpenCV's extra modules](https://github.com/Itseez/opencv_contrib) in the OpenCV build?

[Here is the script for OpenCV](https://github.com/ruslo/hunter/blob/master/cmake/projects/OpenCV/hunter.cmake).

**Comment by ruslo** [comment]
Let's start with this: https://github.com/ruslo/hunter/issues/170

**Comment by ruslo** [comment]
The next step is adding this package to the OpenCV build. Since we have an option `OPENCV_EXTRA_MODULES_PATH` we can add extra CMake arguments similar to [LLVM](https://github.com/ruslo/hunter/blob/b83d6a75ac33cf8bccbdcf7961d4d4bbdf0238e6/cmake/projects/LLVM/hunter.cmake#L56):

```cmake
hunter_add_package(OpenCV-Extra)

# ...

hunter_cmake_args(
    OpenCV
    CMAKE_ARGS
        "OPENCV_EXTRA_MODULES_PATH=${OPENCV-EXTRA_ROOT}/modules"
)

hunter_download(
    PACKAGE_NAME OpenCV
    PACKAGE_DEPENDS_ON OpenCV-Extra
)
```

But I don't think it's a good idea to add such option by default (at least this affect build time, I guess). Usually it's possible to add custom options to the user's config: https://github.com/ruslo/hunter/wiki/example.custom.config.id#custom-cmake-options but it's not our case since we need to call `hunter_add_package(OpenCV-Extra)` to init `OPENCV-EXTRA_ROOT` variable and before `hunter_add_package` we need to parse user's config - i.e. we have cyclic dependency :)

The solution I can offer is to patch OpenCV - add new option `OPENCV_WITH_EXTRA_MODULES`:
```cmake
if(OPENCV_WITH_EXTRA_MODULES)
  hunter_add_package(OpenCV-Extra)
  set(OPENCV_EXTRA_MODULES_PATH "${OPENCV-EXTRA_ROOT}/modules")
endif()
```

You can enable this feature locally by using `LOCAL` option of `HunterGate` module:
```cmake
HunterGate(
    URL # ...
    SHA1 # ....
    LOCAL
)
```

and providing next local config `cmake/Hunter/config.cmake`:
```cmake
hunter_config(
    OpenCV
    VERSION ${HUNTER_OpenCV_VERSION}
    CMAKE_ARGS OPENCV_WITH_EXTRA_MODULES=YES
)
```

@ahundt Does this solution fit your needs?

**Comment by ahundt** [comment]
It sounds like it does but I'm not 100% sure how to add that to my tree.

**Comment by ruslo** [comment]
> It sounds like it does but I'm not 100% sure how to add that to my tree

I will patch OpenCV and will send you updated version of Hunter

**Comment by ruslo** [comment]
@ahundt Hi Andrew,

I've [patched](https://github.com/hunter-packages/opencv/commit/738584dab7a0cb92e1050578a82480960acee643) OpenCV so it has new option OPENCV_WITH_EXTRA_MODULES now. This option is **not** set by default - you have to specify it locally. The easiest way to do it is to add `LOCAL` suboption to `HunterGate` command:

```cmake
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.11.13.tar.gz"
    SHA1 "fc5e12a40b61c326acdd6f1f123f926bf445ad5c"
    LOCAL # use additional user's settings
)
```

and add `OPENCV_WITH_EXTRA_MODULES=YES` to the `CMAKE_ARGS`:

```cmake
hunter_config(
    OpenCV
    VERSION ${HUNTER_OpenCV_VERSION} # inherit global version
    CMAKE_ARGS OPENCV_WITH_EXTRA_MODULES=YES # add custom build option
)
```

Take a look at [wiki page](https://github.com/ruslo/hunter/wiki/example.custom.config.id) for more information. Let me know if you have any questions.

Cheers, Ruslan

**Comment by ahundt** [comment]
awesome, thanks!

**Comment by ruslo** [comment]
Fixed. Closing.
