### ISSUE TITLE
Add libjpegturbo

### ISSUE THREAD

**Issue by hjmallon** [ruslo/hunter#1722]
* I'm interested in package `libjpegturbo`
* Here is official site of package https://www.libjpeg-turbo.org/
* This package is using Git: https://github.com/libjpeg-turbo/libjpeg-turbo
* Used build system: CMake
* This package has no dependencies

**Comment by insufficientchocolate** [comment]
I am intrested in this too. I've tried to use another fork of `libjpegturbo` as depedencies of `leptonica` in hunter. But I found that if there's any other dependencies that use `libjpeg`, the headers will conflict(both package provide header like `jconfig.h`).
I am wondering how to avoid this kinds of conflict. Add it as new a package and user will need to manually check dependency graph to get rid of "vanilla" libjpeg or add it as an option in exsiting libjpeg package to use different fork so that hunter will automatically inject it to other packages depends on it?
Might related to issue https://github.com/ruslo/hunter/issues/1191

**Comment by headupinclouds** [comment]
> Might related to issue #1191

It is the same issue.  You can maintain two HUNTER_ROOT's.

**Comment by hjmallon** [comment]
I think we will need a fork of https://github.com/libjpeg-turbo/libjpeg-turbo to start hacking on to get something to work.

**Comment by ruslo** [comment]
> will need a fork of https://github.com/libjpeg-turbo/libjpeg-turbo

Done: https://github.com/hunter-packages/libjpeg-turbo

Branch `hunter-2.0.1` created, based on the latest `2.0.1` upstream tag.

> I am wondering how to avoid this kinds of conflict. Add it as new a package and user will need to manually check dependency graph to get rid of "vanilla" libjpeg or add it as an option in exsiting libjpeg package to use different fork so that hunter will automatically inject it to other packages depends on it?

There is no such mechanism introduced at this moment, the user has to control everything manually.

**Comment by hjmallon** [comment]
This is available now https://docs.hunter.sh/en/latest/packages/pkg/libjpeg-turbo.html
