### ISSUE TITLE
Split up install directory for each package

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#1811]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**

---

Instead of installing everything into a hunter_root directory we could install each package into it's own subdirectory.

Requirements for a package to do this with:
- needs to be relocatable
- needs to install a `foo-config.cmake` file

For each provided package we set the `foo_DIR` variable for `find_package` to easily find the installed package

My motivation: I had two projects both using Hunter to get the dependencies (lets say `ProjA` and `ProjB`). Both projects have dependency `foo`. `ProjB` also has depency `bar`. `foo` has an optional dependency on `bar`. Now Hunter provides both `foo` and `bar` and `foo` is configured to always use `bar` if available. The result is, that `ProjA` uses `bar` even though this wasn't intended, just because it is installed in the same hunter_root install directory

I'd like to propose an option to instruct Hunter to only use `foo_DIR` variables and don't provide the search path to the hunter_root directory. Maybe even a check to error when I try to use a package, which does not yet support `foo_DIR` linking

**Comment by ruslo** [comment]
It will be much harder to maintain RPATH. If you have layout:
```
/<root>/lib/boo.dylib
/<root>/bin/foo
```

You can set RPATH for `foo` to `@executable_path/../lib` and nothing else need to be done to make a `foo` package relocatable.

If you have layout:
```
/<root-1>/lib/boo.dylib
/<root-2>/bin/foo
```

You will have to modify RPATH each time `<root-*>` created, set it to `@executable_path/../<relative-from-root-2-to-root-1>/lib`. That's pretty tricky, and also it will break the cellar functionality:
- https://docs.hunter.sh/en/latest/reference/layouts/deployed.html#cellar

For Windows, you will have to set `PATH` variable to `/<root-dep-1>/bin;/<root-dep-2>/bin;/<root-dep-3>/bin;...` before running executable `/<root>/bin/foo`. Otherwise dependent DLLs from `/<root-dep-*>/bin` will not be loaded.

> foo has an optional dependency on bar

You should control it with option explicitly instead of relying on the environment:
- https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#environment

**Comment by NeroBurner** [comment]
I haven't thought about RPATH and PATH variables, I was only thinking about the actual building

maybe we can do something like [this](https://github.com/NeroBurner/FAudio/blob/improved_install_shared_libs/cmake/install_shared_libs.cmake) to copy the needed dlls to the install target instead of setting PATH variables

**Comment by ruslo** [comment]
> I haven't thought about RPATH and PATH variables

That's the common one, but in general, anything that makes two packages work together will be tricky.

- boo: library and resources
- foo: executable, depends on library and resources

Layout:
```
/<root>/share/boo-resource.txt
/<root>/bin/foo
```

Solution:
```cpp
std::string foo::resource_path()
{
  return path_to_foo + "../share/boo-resource.txt";
}
```

Layout:
```
/<root-1>/lib/boo.dylib
/<root-2>/bin/foo
```

```cpp
std::string foo::resource_path()
{
  return path_to_foo + "???" + "share/boo-resource.txt";
}
```

> maybe we can do something like this to copy the needed dlls to the install target instead of setting PATH variables

So basically you will reproduce
```
/<root>/lib/boo.dylib
/<root>/bin/foo
```
layout :)

**Comment by NeroBurner** [comment]
yes, but per project install :see_no_evil: 

closing because dependencies are much harder than they first appear ^^
