### ISSUE TITLE
Add "botan" package

### ISSUE THREAD

**Issue by Bjoe** [ruslo/hunter#1897]
* I'm interested in package `botan`

* Here is the official site of package https://botan.randombit.net/

* Official GitHub repository: https://github.com/randombit/botan

* Used build system: custom (python based)

* This package has next dependencies:
  * `ZLIB` (required, available in Hunter: https://docs.hunter.sh/en/latest/packages/pkg/ZLIB.html)
  * `BZip2` (required, available in Hunter: https://docs.hunter.sh/en/latest/packages/pkg/BZip2.html)

---
I already started to [package botan into hunter](https://github.com/Bjoe/hunter/tree/pr.botan) and it works for me (see [pkcs11-botan-poc](https://github.com/Bjoe/pkcs11-botan-poc)), but I need some hints/help how to create a pull request / review / cleanup / test / merge

I have also some more packages in the pipline (see [branches](https://github.com/Bjoe/hunter/branches)):
pkg.PocoCpp
pkg.neopg
pkg.gettext
pkg.taojson
pkg.pegtl
pkg.gnutls
pkg.nettle
pkg.libtasn1
pkg.gmp
pkg.libusb
pkg.OpenSC
pkg.openct
pkg.macchina

I would like to merge this also, but step by step :-)

**Comment by Bjoe** [comment]
[Botan](https://docs.hunter.sh/en/latest/packages/pkg/botan.html) is now added but why I didn`t see it in the [crypto group](https://docs.hunter.sh/en/latest/packages/crypto.html) ?

Unfortunately it is not building for Windows. Should I rename this issue or close this issue and create a new one or only close this issue and that`s it?

**Comment by ruslo** [comment]
> Botan is now added but why I didn`t see it in the crypto group ?

```
.. index::
  single: crypto ; botan

.. _pkg.botan:
```

Will add it to this page:
- https://docs.hunter.sh/en/latest/genindex.html#C

`Crypto` page you've mentioned is here:
- https://github.com/ruslo/hunter/blob/v0.23.206/docs/packages/crypto.rst

> Unfortunately it is not building for Windows. Should I rename this issue or close this issue and create a new one or only close this issue and that`s it?

Since the package is added in any form, let's close it. List of supported platforms can be found in `pkg.botan` branch:
- https://github.com/ingenue/hunter/blob/24b2d6b68466da6904a5d5cd5fd154e935d8d0d6/.travis.yml#L37-L105
- https://github.com/ingenue/hunter/blob/24b2d6b68466da6904a5d5cd5fd154e935d8d0d6/appveyor.yml#L11-L53
