### ISSUE TITLE
Autotools for iOS 

### ISSUE THREAD

**Issue by pretyman** [ruslo/hunter#207]
It would be great to have autotools playing nice with iOS.

Some remarks by @ruslo in getting this done at https://github.com/ruslo/hunter/issues/116#issuecomment-122684821 :

> If you're using Polly toolchain there are some help variables like `IOS_SDK_VERSION` or `IPHONESIMULATOR_ROOT`. Also you may take a look at OpenSSL iOS scheme.

Also, very useful information seems to lie in https://github.com/szanni/ios-autotools 

You can assign this to me. I am creating it as an issue here so I don't forget 
##

**Comment by pretyman** [comment]
A challenge for Autotools is that a single ./configure && make install targets one architecture, while the toolchain for iOS target more than one: 

````
set(IPHONEOS_ARCHS armv7;armv7s;arm64)
set(IPHONESIMULATOR_ARCHS i386;x86_64)
``` 

So what I did, as a preliminary test, I commented the above lines and put only `set(IPHONEOS_ARCHS armv7s)`. I tried to build qt-widgets, but it failed to link: 

````
ld: file is universal (2 slices) but does not contain a(n) armv7s slice: /Users/discipline/.hunter/_Base/xxxxxxx/db18faa/fb18861/Install/plugins/platforms/libqios_debug.a file '/Users/discipline/.hunter/_Base/xxxxxxx/db18faa/fb18861/Install/plugins/platforms/libqios_debug.a' for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)
``` 

So that was no good.

Since Hunter need to support multiple targets for iOS anyway, because that is the standard behavior, when I guess I will have to wrap ExternalProcject_Add for Autotools inside a function to add behavior to treat the iOS scenario.

Essentially what I need to do, is have a  `./configure && make && make install` for each architecture, then look around for the generated static libs with `file(GLOB ...)` and `lipo` them together into `<root-id>/Install` 

I am not yet certain how to implement this:
1. Should I have an ExternalProject_Add for each architecture? If so, how would I know all the projects have finished compiling so I can run `lipo`?
2. Should I have custom `CONFIGURE_COMMAND` that will run `./configure` for each target in a separate directory. Doing the same for the `BUILD_COMMAND` and at the end of the custom `INSTALL_COMMAND`, after `make install`ing all targets, I would run `lipo` to make a universal static library?

Any suggestions are welcome :-)

**Comment by ruslo** [comment]
>  I tried to build qt-widgets, but it failed to link

This is because by default Qt build armv7 + arm64 (see my [note](https://github.com/ruslo/hunter/issues/116#issuecomment-122570872)). Please open separate bug if you're interested in support of other architectures. I think it can be fixed by replacing one line in 'qtbase/mkspecs/macx-ios-clang/qmake.conf` file (see QMAKE_IOS_DEVICE_ARCHS). Also note that simulator's libs can't be found by find_package. I have an idea about fusing device + simulator libraries after install so open one more bug if you're interested in this too :)

> Should I have an ExternalProject_Add for each architecture?

I think yes.

> If so, how would I know all the projects have finished compiling so I can run lipo

You need to create one more project `*-universal` and make it depends on all `*-archN`.

> Should I have custom CONFIGURE_COMMAND that will run ./configure for each target in a separate directory. Doing the same for the BUILD_COMMAND

I think yes. At least this will work for any kind of project (out-of-source friendly/unfriendly, support universal or don't).

> at the end of the custom INSTALL_COMMAND, after make installing all targets, I would run lipo to make a universal static library?

Install stage of `*-universal` external project.

PS This is how OpenSSL work: https://github.com/ruslo/hunter/blob/master/cmake/schemes/url_sha1_openssl_ios.cmake.in

**Comment by pretyman** [comment]
Thanks, your suggestions were extremely useful

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/issues/218#issuecomment-486625419
