### ISSUE TITLE
Fix Qt: link missing libraries

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#257]
https://github.com/headupinclouds/gatherer/commit/7bb5bb8cc1c4feee3e54aa56994e3a89b6369637

**Comment by headupinclouds** [comment]
The next commit provides a working OS X camera example following the suggestion by @pretyman in  #253 : headupinclouds/gatherer@6cef5c86c2dfe1c1727971c058a93c7e3c53074d
The extra linking in that example is all due to camera related plugins.  I haven't found documentation yet that describes these plugin dependencies.  For example, What `Q_IMPORT_PLUGIN(Plugin)` + `object_cast<QQmlExtensionPlugin*>(some_plugin().instance())->registerTypes("Plugin")` calls are required to get the camera working in Android?

**Comment by ruslo** [comment]
Fixed. Example [qt-camera](https://github.com/ruslo/hunter/blob/develop/examples/qt-camera/CMakeLists.txt) compiles/links fine on Windows, Linux, OSX, Android, iOS, but on Linux and Android I got non-working camera. Android version of this example from official release compiled by Qt Creator doesn't work too though.
