### ISSUE TITLE
Add freetype package

### ISSUE THREAD

**Issue by Dinno** [ruslo/hunter#279]
http://www.freetype.org/download.html

**Comment by Dinno** [comment]
I added this package, but I take source archive from SourceForge. Do we need to place sources to your git's organization?

**Comment by ruslo** [comment]
> Do we need to place sources to your git's organization?

No if it's not patched. If future (really far future) I hope all packages will go from upstreams directly.

**Comment by ruslo** [comment]
Closed by https://github.com/ruslo/hunter/pull/284

@Dinno Thanks!

**Comment by ruslo** [comment]
@Dinno I've disabled testing of `analyze` and `ios` toolchains: https://github.com/ruslo/hunter/commit/686a46487593395ee5f6619bfb6c813287eec0ef

Clang analyzer error: https://travis-ci.org/ruslo/hunter/jobs/95130614
```
/.../freetype/Source/src/autofit/afwarp.c:94:15: warning: Value stored to 'xx1max' during its initialization is never read
      FT_Pos  xx1max = warper->x1max;
              ^~~~~~   ~~~~~~~~~~~~~
1 warning generated.
```
Let me know if you want to report/fix it. I will return testing back.

iOS build error: https://travis-ci.org/ruslo/hunter/jobs/95130613
Looks like `freetype` depends on `png`. To fix this you need to "hunterize" freetype by adding `hunter_add_package` instructions. Actually this may result problems on other platforms too since looks like by default `png` from system is taken. See for details: https://github.com/ruslo/hunter/wiki/usr.adding.new.package.with.dependencies

**Comment by Dinno** [comment]
It is strange that hunter package for libpng library is called PNG. Shouldn't it be renamed?

**Comment by ruslo** [comment]
There is [FindPNG](https://cmake.org/cmake/help/latest/module/FindPNG.html) module, it means that `find_package` called this way:
```cmake
find_package(PNG REQUIRED)
```
hence I think it make sense to use `PNG` in Hunter too:
```cmake
hunter_add_package(PNG)
find_package(PNG CONFIG REQUIRED)
```

PNG is a name for project, project can have multiple targets.

**Comment by Dinno** [comment]
freetype's CMakeLists.txt does not install config file for find_package. I think we should add patch project for freetype and add installation instructions for config file.

**Comment by ruslo** [comment]
>  I think we should add patch project for freetype

Created: https://github.com/hunter-packages/freetype
