### ISSUE TITLE
UnicodeDecodeError in jenkins.py on Windows.

### ISSUE THREAD

**Issue by Knitschi** [ruslo/hunter#298]
When I run the jenkins.py for the GoogleTest package I get the following error message:
My Python Verison is 3.4.4

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 81: invalid start byte

Here is the full output.

![jenkins_py_error](https://cloud.githubusercontent.com/assets/11889116/12194790/c1267f68-b5f2-11e5-816e-586582116801.jpg)

**Comment by ruslo** [comment]
Looks like it's a Polly issue: https://github.com/ruslo/polly/blob/c343d0ad3fe7810c3482c84e2a8b1e8ce8685861/bin/detail/call.py#L17

Probably this is because Windows console is not encoding characters in UTF8 which make difference for non-ASCII symbols. My windows locale set to english so it works for me.

Can you try `build.py` from Polly to build some trivial project, like `build.py --toolchain vs-12-2013 --verbose`?

**Comment by Knitschi** [comment]
Seems that you were right. Using build.py for a trivial project yields:
![build-py_with_trivial_project](https://cloud.githubusercontent.com/assets/11889116/12303455/b19d96ee-ba2a-11e5-9385-aa8fda818a35.jpg)
But I can go to "Control Panel" -> "Regional and Language Options" -> Tab: "Administrative" and change "Language for non-Unicode programs" to English, then the Problem does not occur.

**Comment by ruslo** [comment]
> Seems that you were right. Using build.py for a trivial project yields

Thanks for testing, so let's close this one since it's not Hunter bug. I've openned Polly issue:
* https://github.com/ruslo/polly/issues/62
