### ISSUE TITLE
"A Packaging System for C++"

### ISSUE THREAD

**Issue by LegalizeAdulthood** [ruslo/hunter#346]
[This standards proposal](http://open-std.org/JTC1/SC22/WG21/docs/papers/2016/p0235r0.pdf) is an interesting read.

Discuss :smile_cat:
##

**Comment by ruslo** [comment]
Separate concepts
===============

Looks like they're trying to get rid of build system. I think it's not something achievable on practice in observable future or even not possible in general. When I have line `#include <boost/system.hpp>` I want to have an opportunity to compile this code with Boost 1.57 and then with 1.58. Who will be responsible for such switch? If compiler how it will looks like? What about same compiler but different flags (c++11, c++14)?

I see the whole picture in a such way: C++ code is about abstraction/interface, CMake code is about "implementation". I.e. when I have C++ code
```
#include <gtest/gtest.h>
```

It's CMake responsibility to decide what toolchain (MSVC, iOS, Android), version, URL etc. to use to download GTest and build.

Same with optional packages:
```
#ifdef (USING_ASIO_BACKEND)
# include <asio.h>
#elif (USING_CURL_BACKEND)
# include <curl.h>
#else
# ...
#endif
```

Separating concepts is one of the ways to reduce complexity.

However what will be useful is if compiler will produce some helper info about header/sources that CMake (or other tool) can check. For example if `foo.hpp` use `FOO_FEATURE_1` macro then CMake should check that this macro belongs to usage requirements.

JSON for MANIFEST
================

I've mentioned already that I see no benefits of using JSON for specifying build options in context JSON vs. CMake (e.g. see [biicode](https://github.com/ruslo/hunter/issues/54#issuecomment-81729651)). I think CMake is minimum requirement (see previous section) and CMake is good enough (see Hunter package manager). Also raw JSON file can't be good enough for substituting build system. JSON is simple - build system is not simple, it's a full language: custom build steps, generated files, non trivial chain of conditions etc.

Questions
========

> If semantic versioning is enabled for a package then the compiler, when selecting among multiple available packages, must select the highest-numbered compatible package.

It should select determinable version. Otherwise we will have different version on different machines - so it will be very hard to reproduce build errors.

There are some places I don't understand at all:

> CMake can’t, won’t, and shouldn’t use the same package format as Visual Studio.

I can download package using `hunter_add_package(Foo)` and find it by `find_package(Foo CONFIG REQUIRED)` and generate Visual Studio project with such settings. So what is the exact part that "can't be done" with CMake?

> Compilers already keep track of a list of files to compile
> Compilers already perform checks to see if they’ve already built a file.

It's not compiler, it's a build system. For example both tasks can be done with make.

Other
=====

Reddit discussion:
* https://www.reddit.com/r/cpp/comments/474vsf/a_packaging_system_for_c_proposal/

**Comment by LegalizeAdulthood** [comment]
The one thing in their proposal that I liked was the idea of consuming a package by adding a single line of code to my source file.  However, I wonder if this "easy to use" idea will be useful for real world projects and not just n00b toy examples.  They say they've implemented it in a fork of clang, what I wonder is why this hasn't been contributed back to clang for the community to try out?  This seems like one of those standards proposals that needs real world experience for some time before we write this in stone.

**Comment by ruslo** [comment]
Closing inactive discussion.
