### ISSUE TITLE
Add 'leptonica' package

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#460]
GitHub: https://github.com/DanBloomberg/leptonica
Hunterized: https://github.com/hunter-packages/leptonica
##

**Comment by pretyman** [comment]
Should the hunter package be called `leptonica` or with capital L as `Leptonica`? 

I ask because the tesseract-ocr uses `find_package(Leptonica)` and the *.cmake files generated are named:

LeptonicaConfig-version.cmake 
LeptonicaConfig.cmake
LeptonicaTargets.cmake

but the project is named `leptonica` on its repository, and the library is named `libleptonica` (historically it used to be called `liblept`)

**Comment by ruslo** [comment]
> What's your call?

In theory I think everything should be lowercase: `hunter_add_package(leptonica)`, `find_package(leptonica CONFIG REQUIRED)`, `leptonicaConfig*.cmake`, `project(leptonica)`, `namespace leptonica {`. On practice it can be called anyhow, just document it.

**Comment by xsacha** [comment]
Protobuf/protobuf has the same uppercase/lowercase issue

Should this be consistent project-wide?

**Comment by ruslo** [comment]
> Should this be consistent project-wide?

It should but I can't control all the packages. If we are talking about protobuf I think it **was** consistent, but then the upstream code changed.

**Comment by xsacha** [comment]
I chose capital L since it is done that way upstream and by tesseract (seems to be its primary usage).
This requires the least amount of changes.

**Comment by ruslo** [comment]
Closed by https://github.com/ruslo/hunter/pull/815
