### ISSUE TITLE
LAN only build environment

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#517]
I'd like to build a LAN-Only build environment. The Internet access is restricted, so not every PC is allowed to connect to github to use hunter packages and download the sources. Is it possible to provide a local hunter gate with LAN-only packages?

There are several Projects I need to maintain. How can I easily keep those projects up to date with the used packages and the hunter build system?

And one last question: is it possible to have a link to the latest version of a package? Currently I'm toying around with ExternalProject using no hash and a symlink at the server which I update to the latest version
##

**Comment by ruslo** [comment]
> Is it possible to provide a local hunter gate with LAN-only packages?

In general you can use any paths in URL in `hunter.cmake` file so you can just set `file:///server/downloads/boost_1_61_0.tar.bz2` instead of `https://downloads.sourceforge.net/project/boost/boost/1.61.0/boost_1_61_0.tar.bz2`. However I was thinking about `HUNTER_DOWNLOAD_SERVER` feature when you can apply this globally or per package. I.e. you set `HUNTER_DOWNLOAD_SERVER=file:///server/downloads` and instead of standard URL Hunter try `file:///server/downloads/boost_1_61_0.tar.bz2`.

> There are several Projects I need to maintain. How can I easily keep those projects up to date with the used packages and the hunter build system?

Not sure what this question is about. You want to use latest Hunter release for them?

> And one last question: is it possible to have a link to the latest version of a package?

Usually latest version of package set in global `config.cmake` it is available by `HUNTER_<package>_VERSION` variable. See more details here: https://github.com/ruslo/hunter/wiki/example.custom.config.id#version-inheriting

**Comment by NeroBurner** [comment]
Is the `HUNTER_DOWNLOAD_SERVER` functionality implemented or is this a future development?

> Not sure what this question is about. You want to use latest Hunter release for them?
My question was actually two questions:
- how can I easily keep Hunter updated to be the latest available version for many different projects? Do I have to update the `cmake/HunterGate.cmake` for each project I use? How do I know I need to update the HunterGate module?
- is it possible to download always the latest release of a package. So instead of downloading the package foolib v0.1.0 I download package foolib current.

I think version inheriting is the question to the second answer. If I understand correctly I can configure cmake to always use the default version provided by Hunter-Archive file

**Comment by ruslo** [comment]
> Is the HUNTER_DOWNLOAD_SERVER functionality implemented or is this a future development?

Nope, just an idea. I've created feature request: https://github.com/ruslo/hunter/issues/521

> always use the default version provided by Hunter-Archive file

Yes

**Comment by ruslo** [comment]
Closing inactive discussion.
