### ISSUE TITLE
msgpack is broken

### ISSUE THREAD

**Issue by tatraian** [ruslo/hunter#532]
I could compile msgpack without error with version 14.14. But now with master (15.33) I couldn't. The problem is that now we don't found `OpenSSL::Crypto`. I think something changed and now not the updated `FindOpenSSL.cmake` runs but the built in, but this is just a tip.

**Comment by ruslo** [comment]
What platform we are talking about?

Here are the tests:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1015
* https://travis-ci.org/ingenue/hunter/builds/163176929

Looks like Android not working. But if the reason of failure is OpenSSL then that's because OpenSSL doesn't work on Android. See testing, there is no `android-*` toolchain:
* https://travis-ci.org/ingenue/hunter/builds/162921298

**Comment by tatraian** [comment]
Sorry. Than somthing went wrong during merge at my side.
