### ISSUE TITLE
How does this effort relate to biicode?

### ISSUE THREAD

**Issue by LegalizeAdulthood** [ruslo/hunter#54]
[biicode](http://web.biicode.com/features/cpp/) appears to address many of the same issues as Hunter.  How is it different?  How is it the same?

**Comment by ruslo** [comment]
In short Hunter try to be a thin wrapper for existing techniques and biicode try to be a stand-alone project just using CMake under the hood. This is what I see for now with my little experience. I will add some examples of what I mean later.

**Comment by ruslo** [comment]
### Diff A (binary vs CMake module)

You've already ask me about why Hunter [is not binary executable](https://github.com/ruslo/hunter/issues/4) so now we can compare it on practice :)
Let's see how regular CMake's users build projects (instead of `wget *.tar.gz` may be `git clone`, `svn checkout`, etc.):

##### CMake workflow (without 3rd party dependencies)
```
1. Install CMake (`apt-get install cmake`)
2. Download project (`wget https://github.com/.../awesome-project.tar.gz`)
3. Generate project (`cmake -Hawesome-project -B_builds`)
4. Build project (`cmake --build _builds`)
```

#####  CMake workflow (with 3rd party dependencies)
```
1. Install CMake (`apt-get install cmake`)
1a. Install dependencies (like `apt-get install libboost-dev` or `brew install boost`)
2. Download project (`wget https://github.com/.../awesome-project.tar.gz`)
3. Generate project (`cmake -Hawesome-project -B_builds`)
4. Build project (`cmake --build _builds`)
```

Using Hunter package manager build commands are quite the same:

##### Hunter workflow (with or without dependencies)
```
1. Install CMake (`apt-get install cmake`)
1a. *Not needed*
2. Download project (`wget https://github.com/.../awesome-project.tar.gz`)
3. Generate project (`cmake -Hawesome-project -B_builds`) (dependencies installed automatically)
4. Build project (`cmake --build _builds`)
```

Actually you can disable Hunter by `HUNTER_ENABLED=OFF` and workflow remains the same:

##### CMake workflow (with 3rd party dependencies)
```
1. Install CMake (`apt-get install cmake`)
1a. Install dependencies (like `apt-get install libboost-dev` or `brew install boost`)
2. Download project (`wget https://github.com/.../awesome-project.tar.gz`)
3. Generate project (`cmake -Hawesome-project -B_builds -DHUNTER_ENABLED=OFF`)
4. Build project (`cmake --build _builds`)
```

#####  Biicode workflow
```
0. Install biicode (`apt-get install biicode`)
1. Install CMake (`apt-get install cmake` or `bii setup:cpp`)
2. Download project (`wget https://github.com/.../awesome-project.tar.gz`)
3. Generate project (`bii cpp:configure`) # not needed if using default CMake arguments
4. Build project (`bii cpp:build`)
```

Also some extra work needs to be done to use other tools. For example to open CMake GUI you still need to use Biicode explicitly from command line:

##### Biicode workflow (CMake GUI)
```
0. Install biicode (`apt-get install biicode`)
1. Install CMake (`apt-get install cmake` or `bii setup:cpp`)
2. Download project (`wget https://github.com/.../awesome-project.tar.gz`)
3. Generate project (`bii cpp:configure`) # you must create master CMakeLists.txt file
3a. Open myprojects/cmake/CMakeLists.txt in CMake GUI and run "Generate"
4. Run "Build"
```

Same with Qt Creator, but on step 3a hit "Run CMake" button.

Well I understand that it's just a matter of habit but anyway. Also binary can cause some unpredictable surprises. For example after I've downloaded Biicode I found out that it doesn't work on os x 10.8, though my build tools like Xcode, clang, CMake (and hence Hunter) works fine.

Probably one of the reasons that Biicode is binary is that you can generate CMake project without actually having CMakeLists.txt, but in this case it matters only for "Hello world" application. If you project is big enough and have some build options you must know how to work with CMake commands. Also Biicode can be used not only for CMake/C++ projects (?).

Note: I know that sometimes CMake doesn't have enough flexibility/simplicity. I personally have CMake-build wrapper too: https://github.com/ruslo/polly. But I'm looking at this project as an experimental stuff that can be moved after testing to other products like Hunter (build-in toolchains) or CMake (there is a bug/discussion in CMake mailing list about functionality similar to `--open` option)

**Comment by ruslo** [comment]
### Diff B (ini format vs CMake code)

As you can see [here](http://docs.biicode.com/c++/using_biicode/blocks.html#biicode-conf) biicode.conf is ini-like configuration file. This is probably inspired by the existent package managers like [npm](https://docs.npmjs.com/files/package.json) or [cocoa pods](http://guides.cocoapods.org/using/the-podfile.html), but in fact I think it have no benefits against simple CMake code. Actually since CMake used to build stuff it fit much better. So assume we have some package dependency only for windows. CMake code:

```cmake
if(WIN32)
  find_package(WinSpecific REQUIRED)
  target_compile_definitions(... WITH_WIN_SPECIFIC=1)
endif()
```

Using Hunter package manager it can be solved by:

```cmake
if(WIN32)
  hunter_add_package(WinSpecific)
  find_package(WinSpecific REQUIRED)
  target_compile_definitions(... WITH_WIN_SPECIFIC=1)
endif()
```

I don't know if there is an option in Biicode for such job, but I assume it will be looked like this:

```
[requirements]
  [windows]
    author/WinSpecific
```

I think logical connection is discarded here, see CMake code remained:

```cmake
if(WIN32)
  target_compile_definitions(... WITH_WIN_SPECIFIC=1)
endif()
```

Now think about some widely-used pattern like this:

```cmake
if(FOO_TESTS)
  find_package(GTest REQUIRED)
endif()

if(FOO_DOCUMENTATION)
  find_package(Doxygen REQUIRED)
endif()

if(FOO_SECURED)
  find_package(OpenSSL REQUIRED)
endif()
```

in terms of Hunter package manager it's quite transparent:

```cmake
if(FOO_TESTS)
  hunter_add_package(GTest)
  find_package(GTest REQUIRED)
endif()

if(FOO_DOCUMENTATION)
  hunter_add_package(Doxygen)
  find_package(Doxygen REQUIRED)
endif()

if(FOO_SECURED)
  hunter_add_package(OpenSSL)
  find_package(OpenSSL REQUIRED)
endif()
```

**Comment by ruslo** [comment]
### Diff C (adaptation overhead)

Note that if you have CMake project without dependency you can add it to Hunter without changing any code at all. And for the non-CMake project without dependencies there is no need to change the package code, you only need to use custom build scheme.

Example 1:
 * Hunter GTest only diffs from official release in adding install target (it's out of this discussion why GTest have no install target by default): https://github.com/hunter-packages/gtest/commit/79bd2ae98ab0c24859c4cbc89355804fa31ae98e
 * As you can see here extra code needed to integrate GTest into Biicode: https://github.com/davidsanfal/gtest/blob/57d6ad126b73ce3e059d0b49a745c92d750e30d6/CMakeLists.txt#L32

Example 2:
* OpenSSL used as is. I think it's kind of imporant for security reason to not to change any code, even if it's only build-related: https://github.com/ruslo/hunter/blob/master/cmake/projects/OpenSSL/hunter.cmake#L28:
```cmake
hunter_add_version(
    PACKAGE_NAME
    OpenSSL
    VERSION
    "1.0.1d"
    URL
    "https://github.com/openssl/openssl/archive/OpenSSL_1_0_1d.tar.gz"
    SHA1
    d427eaf3e7e399f7f5562e00eebd6f2412903339
)
```
* As far as I can see Biicode use patched version: https://www.biicode.com/lasote/lasote/openssl/master/3/biicode.conf

For project with dependencies you only need to add one `HunterGate` command and `hunter_add_package` command for each dependency ([example](https://github.com/hunter-packages/libssh2/commit/5deb961fd26f8598c383366772bd8c8364167610)):

```cmake
project(Foo)
HunterGate(
    URL ....
    SHA1 ...
)

hunter_add_package(Roo)
find_package(Roo REQUIRED)

hunter_add_package(Bar)
find_package(Bar REQUIRED)
```

for Biicode you need to rewrite your code in terms of `BII_BLOCK_TARGET`. As far as I see in example in [documentation](http://docs.biicode.com/c++/building.html#cmakelists-txt):

```cmake
IF(BIICODE)
  ADD_BIICODE_TARGETS()
  TARGET_LINK_LIBRARIES(${BII_BLOCK_TARGET} INTERFACE pthread)
  TARGET_LINK_LIBRARIES(${BII_LIB_TARGET} PUBLIC pthread)
ELSE()
   # Your regular project configuration here
ENDIF()
```

**Comment by ruslo** [comment]
### Diff D (Code is not shared)

If I create two projects that depend on GTest:

```bash
> bii init project1
> bii init project2
```

and run `bii cpp:build` for each of them - GTest will be built twice. Hunter store resulting library in kind of root location, like system: `/usr/lib/libgtest.a`, but customizable: `<root-id>/lib/libgtest.a`. So any number of packages can reuse this library. Probably you can orginize your Biicode layout like this:

```
blocks/ruslo/-
             - foo # use GTest
             - boo # reused!
```

but you sometimes have no control of project location. For example jenkins-ci configuration result next project layout for matrix `{Debug,Release}x{A,B}`:

```
workspace/<proj-name>/CONFIG/Debug/TOOLCHAIN/A
workspace/<proj-name>/CONFIG/Debug/TOOLCHAIN/B
workspace/<proj-name>/CONFIG/Release/TOOLCHAIN/A
workspace/<proj-name>/CONFIG/Release/TOOLCHAIN/B
```

For the small projects like GTest it doesn't matter in practice but if you have a huge project I think it definitely will be the problem.

**Comment by ruslo** [comment]
### Diff E (backward compatibility)

If you're planning sometimes use your old build manager (like apt-get, brew or may be CMake super-build) or you plan to experiment a little bit, you can set `HUNTER_ENABLED=OFF` and all `HunterGate` and `hunter_add_package` commands will be ignored. In case of Biicode in fact as far as I understand you need to support two types of build - CMake and Biicode. From [documentation](http://docs.biicode.com/c++/building.html#add-biicode-targets):

```cmake
if(BIICODE)
  ADD_BIICODE_TARGETS()
  SET_TARGET_PROPERTIES(${BII_BLOCK_TARGET} PROPERTIES COMPILE_DEFINITIONS "IOV_MAX=255")
else()
  add_executable(foo source1.cpp source2.cpp) # DRY violation, source files listed in biicode.conf already (?)
  SET_TARGET_PROPERTIES(foo PROPERTIES COMPILE_DEFINITIONS "IOV_MAX=255")
  TARGET_INCLUDE_LIBRARIES(foo "./include") # DRY violation, already in [include] section (?)
endif()
```

Actually I'm kind of confused here since I'm not sure how I can build two targets, like two libraries (?)

As a result Biicode have a totally different target after install. E.g. GTest build produces target `libgoogle_gtest.a`. Usually GTest have `libgtest.a` and `libgtest_main.a`. So I can't adapt my regular testing since GTest missing library with main function.

**Comment by ruslo** [comment]
### Diff F (File based dependency manager)

* http://blog.biicode.com/file-based-cpp-dependency-manager/

This is feature of Biicode and Hunter is not designed to manage any of such activity, but I want to mention it. Well this is a great idea in general, but I'm kind of pessimistic about can it be implemented in near future correctly without c++ standard support (hence support of compilers; well, all of the major compilers if you want to be cross-platformic). Back to the GTest, simple example:

```cpp
#if defined(_WIN32)
# include <google/gtest/gtest.h>
#endif
```

```bash
> uname
Darwin
> bii find
...
Find resolved new dependencies:
    google/gtest: 10
...
> bii cpp:build
# GTest built but not used actually
```

Same with CMake build option:

```cmake
if(USE_CURL)
  add_definitions(-DUSE_CURL=1)
elseif(USE_ASIO)
  add_definitions(-DUSE_ASIO=1)
else()
  ...
endif()
```

```cpp
#if (USE_CURL)
# include <curl/curl.h>
#elif (USE_ASIO)
# include <asio/asio.hpp>
#else
# include <...>
#endif
```

so I think only compiler knows what is the dependency exactly in this case.

More of this some dependencies have the same include path:

```cpp
#include <iostream> // libc++ or libstdc++ ?
#include <mpi.h> // Open MPI or MPICH2 ?
```

so it's only 3rd party manager responsibility to decide what to load exactly.

**Comment by ruslo** [comment]
### Diff G (Toolchain build)

Both Hunter and Biicode support custom toolchain build: http://docs.biicode.com/c++/building.html#using-a-custom-tool-chain. But in case of Biicode you need to create separate project to use different toolchain without overwriting each other. So let's guess we have two toolchains: `libcxx` and `libstdcxx`. I have a project, want to hack it a little bit and test:

```bash
> git clone https://myproject/location/project.git
> bii init --somehow
> # hack the code
> bii cpp:configure -t libcxx
> bii cpp:build
> bii cpp:configure -t libstdcxx # now old build lost and will be rebuild on new '-t libcxx' configure from scratch
```

Hunter workflow can use both builds simultaneously from the same source code (note that source code is "dirty"/"experimental"):

```bash
> cmake -H. -B_builds/libcxx -DCMAKE_TOOLCHAIN_FILE=libcxx.cmake
> cmake --build _builds/libcxx
> cmake -H. -B_builds/libstdcxx -DCMAKE_TOOLCHAIN_FILE=libstdcxx.cmake
> cmake --build _builds/libstdcxx
```

By the way I don't see how I can build Debug/Release with Biicode from the same directory.

Also flags from toolchain must be forwarded to non-CMake projects too. Here is Biicode bug:

```bash
bii cpp:configure -t libcxx -DCMAKE_VERBOSE_MAKEFILE=ON
bii cpp:build
/.../.biicode/boost/1.57.0/stage/lib/libboost_filesystem-clang-darwin42-mt-1_57.a
```

```bash
bii cpp:configure -t libstdcxx -DCMAKE_VERBOSE_MAKEFILE=ON
bii cpp:build
/.../.biicode/boost/1.57.0/stage/lib/libboost_filesystem-clang-darwin42-mt-1_57.a
```

which lead to undefined symbols linker errors:

```
  Undefined symbols for architecture x86_64:
    "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const", referenced from:
```

Hunter builds two versions of boost for both toolchains and works correctly:

```bash
> cmake --build _builds/libcxx
... -std=c++11 -stdlib=libc++ /.../_Base/264a0bd/78005b3/Install/libcxx/lib/libboost_filesystem-mt.a
> cmake --build _builds/libstdcxx
... -std=c++11 -stdlib=libstdc++ /.../_Base/264a0bd/78005b3/Install/libstdcxx/lib/libboost_filesystem-mt.a
```

**Comment by ruslo** [comment]
biicode is off:
* https://twitter.com/biicode/status/697196264774103040
* http://blog.biicode.com/biicode-just-the-company-post-mortem/index.html

As far as I understand there are some guys from biicode that continue similar work in this project:
* https://www.conan.io/

From the brief overview I see that they are using quite the same approach as biicode, so the difference will be quite the same, e.g. [Diff B: ini vs CMake](https://github.com/ruslo/hunter/issues/54#issuecomment-81729651).

**Comment by bhack** [comment]
Seems that could be some integration [between Conan and Cmake](http://conanio.readthedocs.io/en/latest/integrations/cmake.html).

**Comment by ruslo** [comment]
> Seems that could be some integration between Conan and Cmake

@bhack Not sure I understand what you're trying to say here.

**Comment by bhack** [comment]
Just that you can use conan feature trougth Cmake generators.

**Comment by ruslo** [comment]
> Just that you can use conan feature trougth Cmake generators

This discussion was about `biicode` originally. I just noted that now it's `conan`, however some diffs remain the same like `Diff B`. As far as I understand `conan` use `conanfile.txt` to hold information about dependencies so it's still valid, right?

@bhack you're trying to add some new `diff` or trying to say that some diff is obsolete, or what?
