### ISSUE TITLE
CMAKE_DEBUG_POSTFIX

### ISSUE THREAD

**Issue by dvirtz** [ruslo/hunter#542]
Hunter sets `CMAKE_DEBUG_POSTFIX` to `d` but doesn't it switch it off when it's done.
I don't want it to affect my libraries as well.
Currently I'm forced to `unset(CMAKE_DEBUG_POSTFIX CACHE)` manually.
Is that a bug on Hunter?
##

**Comment by ruslo** [comment]
> Hunter sets CMAKE_DEBUG_POSTFIX to d but doesn't it switch it off when it's done.

It does set it in case there is no default value already. We can't have empty postfixes for different build types because in this case installed libraries will be overwritten by each other.

**Comment by dvirtz** [comment]
can't it be set to it's original value after Hunter runs?

**Comment by ruslo** [comment]
If we will set it back to original value then postfix `d` will not be applied to current project and we will have issues that I've mentioned earlier. This code should work "nice":

```cmake
HunterGate(URL ... SHA1 ...)
add_library(foo ...)
```

I'm not sure I understand your problem. If you want to have custom posfix Hunter will use it. If you want it to set to empty value then you will have a problems while installing several build types.

**Comment by dvirtz** [comment]
I don't install several build types only Release builds.
I'll stick to my current workaround in the meantime.

**Comment by ruslo** [comment]
> only Release builds

So why do you care about `CMAKE_DEBUG_POSTFIX` at all?

**Comment by dvirtz** [comment]
I have unit tests which load the libraries dynamically and also sometimes I
want to override the Release install with the Debug libraries for debugging
purposes.

**Comment by ruslo** [comment]
Actually I guess it is possible to remove modification of `CMAKE_*_POSTFIX` variables because they are set explicitly in CMake scheme for 3rd parties anyway. However this feature show that your approach is not extendable, I think you should not rely on the name of the library, you should use `$<TARGET_FILE_NAME:tgt>` generator expression instead.

**Comment by dvirtz** [comment]
The default value for `CMAKE_<CONFIG>_POSTFIX` is empty. Why should using Hunter change that?
If I'm not mistaken, the whole debug postfix is a Windows convention. The Linux way is changing LD_LIBRARY_PATH to point to the Debug libs, no? This is the approach I'm using.

**Comment by ruslo** [comment]
> If I'm not mistaken, the whole debug postfix is a Windows convention. The Linux way is changing LD_LIBRARY_PATH to point to the Debug libs, no?

For Windows you can do the same by changing PATH (if we are talking about DLL). Usually package managers doesn't provide more build types than just Release, so I will not say there are some conventions. Using different posfixes for different build types will work for all platforms, CMake do support this part nicely.

> The default value for CMAKE_<CONFIG>_POSTFIX is empty. Why should using Hunter change that?

Originally this was introduced because it doesn't make sense to have empty debug postfix since installed libraries will be rewrittern, however posfix will be added for 3rd party in CMake scheme so I think this logic can be removed. Please send pull request with fix. Need to run some tests.

**Comment by dvirtz** [comment]
Thanks for your patience.

> Please send pull request with fix

I'll do that.

**Comment by ruslo** [comment]
Closing inactive discussion.

**Comment by kaihowl** [comment]
As far as I can tell, this issue is still present in recent versions of Hunter and there never has been a PR to fix this. If the https://github.com/ruslo/hunter/issues/542#issuecomment-256265073 comment by @ruslo is still correct, I would like to do the PR. Yet, I do need some pointers as I could only find a single place where `CMAKE_<CONFIG>_POSTFIX` is set. Unless https://github.com/ruslo/hunter/blob/master/cmake/schemes/url_sha1_cmake.cmake.in#L125 ff is what you were referring to.

**Comment by Boris-Rasin** [comment]
It's even worse: first time I run cmake, debug target is configured without postfix, but on subsequent cmake runs, "d" is appended to debug target name. [Example](https://github.com/scapix-com/example1/blob/master/project/vs_cpp.cmd).

Also, in some cases changing library name makes it completely unusable. Python, for example, will not load library if it's name is different from name returned by exported API. [Example](https://github.com/scapix-com/example1/blob/master/project/vs_python.cmd).

**Comment by ruslo** [comment]
> If the #542 (comment) comment by @ruslo is still correct, I would like to do the PR

@kaihowl It's here:
- https://github.com/ruslo/hunter/blob/fb1a8563a4e8356c98bd028013ff0cb1cc10ef7e/cmake/modules/hunter_apply_gate_settings.cmake#L89-L105

Currently, `POSTFIX` used in `Toolchain-ID` calculation, so it might be not a trivial change:
- https://github.com/ruslo/hunter/blob/e1981c5d7ca5cb628eef78803e35e2369d802e9a/cmake/modules/hunter_calculate_toolchain_sha1.cmake#L84-L91
- https://github.com/ruslo/hunter/blob/76848a693a891271179ec42c82cf978243a82187/scripts/create-toolchain-info.cmake#L65-L69

**Comment by ruslo** [comment]
> first time I run cmake, debug target is configured without postfix, but on subsequent cmake runs, "d" is appended to debug target name. Example.

@Boris-Rasin Please create a minimal example to reproduce. See:
- https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs

Make sure you haven't hit this pattern:
- https://cgold.readthedocs.io/en/latest/tutorials/variables/regular.html#cache-confusing
