### ISSUE TITLE
OpenCL cl.hpp

### ISSUE THREAD

**Issue by wheybags** [ruslo/hunter#614]
Hey, there is a standard c++ wrapper header that is normally distributed in the include dir of OpenCl vendors sdks, would it be possible to add this to the OpenCL package? It's available under a liberal license from khronos: https://www.khronos.org/registry/cl/api/

**Comment by wheybags** [comment]
ping @caseymcc

**Comment by caseymcc** [comment]
Yeah I use it as well. Planned to create another package for it as it is not required for OpenCL. I haven't done it though as the sub 2.0 version requires python to be installed in order build the hpp with variadic templates "support". I am not sure how to handle that yet other than to note that you need python. Might be nice to have python as a package as well put I am not sure the probability of that yet.

**Comment by wheybags** [comment]
Does it need to be built? It's just a header no?

**Comment by caseymcc** [comment]
for 2.0+ it is just a header, but 1.x is built from a template file. In order to replicate variadic templates they use python to create multiple duplicate functions with ever increasing input variables (to some maximum). So it has to be "built". Since we seem to maintain separate forks of the original code to hunterize them it could be maintained as just a header, however I think the philosophy is to keep them as close to the original as possible, I believe the goal to be that the hunterization be in the original fork. But I could be wrong.

**Comment by dvirtz** [comment]
> Might be nice to have python as a package as well but I am not sure the probability of that yet.

That would be super awesome. There's a CMake-ified python at https://github.com/python-cmake-buildsystem/python-cmake-buildsystem. Maybe it's possible to use it?

**Comment by ruslo** [comment]
> I am not sure how to handle that yet other than to note that you need python.
> Might be nice to have python as a package as well but I am not sure the probability of that yet

See https://github.com/ruslo/hunter/issues/388, as a workaround you can use system version of Python, need to check it can be found and return user error if not.

> however I think the philosophy is to keep them as close to the original as possible

Yes

> I believe the goal to be that the hunterization be in the original fork

Yes

**Comment by caseymcc** [comment]
Submitted a package for this https://github.com/ruslo/hunter/pull/635, requires python on the system for cl.hpp.

**Comment by ruslo** [comment]
Closing inactive discussion.
