### ISSUE TITLE
Could not find ZLIB

### ISSUE THREAD

**Issue by tdauth** [ruslo/hunter#622]
I am using Hunter on Fedora and getting this error:
```
CMake Error at /home/peterausdemall/.hunter/_Base/Download/Hunter/0.16.15/6974c21/Unpacked/cmake/find/FindZLIB.cmake:57 (find_package):
  Could not find a package configuration file provided by "ZLIB" with any of
  the following names:

    ZLIBConfig.cmake
    zlib-config.cmake

  Add the installation prefix of "ZLIB" to CMAKE_PREFIX_PATH or set
  "ZLIB_DIR" to a directory containing one of the above files.  If "ZLIB"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:94 (find_package)
```

The error appears with the latest release of Hunter, too. I have installed the package "zlib-devel" and the file "/usr/share/cmake/Modules/FindZLIB.cmake" does also exist.

**Comment by caseymcc** [comment]
I think more information on your cmake file is needed to help out.

For hunter installing the os package "zlib-devel" is of little use. Hunter will not look for those packages as it expects to build zlib from its own package. You need to make sure that you have hunter_add_package(ZLIB) in your cmake file before calling find_package(ZLIB CONFIG REQUIRED). There is an example https://github.com/ruslo/hunter/tree/master/examples/ZLIB (most packages have and example which is used for testing), there you will see it used as follows

```
# download
hunter_add_package(ZLIB)

# now can be used
find_package(ZLIB CONFIG REQUIRED)

add_executable(foo main.c)
target_link_libraries(foo ZLIB::zlib)
```

there is also an example in there on how to use it in compatibility mode (using the ZLIB_INCLUDE_DIRS and ZLIB_LIBRARIES, rather than target ZLIB::zlib). hunter_add_package will download the version of ZLIB given (either from the default config or project defined config) compile it and install it to a folders based on a SHA1 hash of the os/toolchain/compiler options. The find_package will then be directed to the hunter installed version.

**Comment by tdauth** [comment]
Ok I didnt know it requires hunter_add_package(ZLIB) automatically when I add find_package(ZLIB REQUIRED) somewhere.
