### ISSUE TITLE
Understanding the Eigen Package

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#623]
I'm working on Ubuntu 16.04. When installing `libeigen3-dev` the file `/usr/lib/cmake/eigen3/Eigen3Config.cmake` is installed. Therefore the eigen package can be found with `find_package(Eigen3 REQUIRED)` and the include dir is saved in `EIGEN3_INCLUDE_DIRS`.

But with hunter one needs the lines
```
hunter_add_package(Eigen)
find_package(Eigen)
```
but neither `Eigen3_INCLUDE_DIRS` nor `Eigen_INCLUDE_DIRS` is set

On both Hunter and Ubuntu a file `share/pkgconfig/eigen3.pc` is installed. With the only difference of the variable `prefix` being set to either `/usr` or  the hunter build directory.

After some more digging I've found the file `${HUNTER_ROOT}/cmake/find/FindEigen.cmake`. There a target `Eigen::eigen` is defined

To support both Hunter and Ubuntu a CMakeLists file would need to look as follows:
```
hunter_add_package(Eigen)
add_executable(eigen_test main.cpp)
if (HUNTER_ENABLED)
	find_package(Eigen REQUIRED)
	target_link_libraries(eigen_test PRIVATE Eigen::eigen)
else()
	find_package(Eigen3 REQUIRED)
	message("target_include_directories(eigen_test PRIVATE ${EIGEN3_INCLUDE_DIRS})")
	target_include_directories(eigen_test PRIVATE ${EIGEN3_INCLUDE_DIRS})
endif()
```

I'd like to unify the the approach of finding and adding the Eigen header files. A few approaches I could think of:
- supply the Upstream Eigen package with a `FindEigen3.cmake` file, which is installed just like the `eigen3.pc` file
- Rename the Hunter package to `Eigen3` (`project/Eigen` and `find/FindEigen.cmake`) and provide the `EIGEN3_INCLUDE_DIRS` variable
- somehow use the already generated `eigen3.pc`-file as hints

What do you guys think?

---

**Comment by caseymcc** [comment]
Take this all with a grain of salt as I haven't been using/working with hunter long (and defiantly not a final authority). I believe the idea behind hunter is for it to ignore (as much as possible) the os packages. Mainly for the reason of cross compiling, you don't want to get the local os package pulled in during the compile for some other os. Providing fallback or look ups on os packages would likely cause more issues than it solves.

It is also unfortunate that Eigen as chosen Eigen3 as the package name as hunter has the version information built in making the 3 redundant and for hunter's consistency I don't think adding Eigen3 would be preferred over just Eigen.

As for you points, here are my thoughts:

- better to keep hunter and os packages as independent as possible
- Again I dont think accepting Eigen3 as a name makes sense in hunter. As for the include/lib directories as far I can tell importing targets like Eigen::Eigen seems to be the direction of cmake in general. When the target is imported through the config it can provide addition information to the cmake build about what is required to use the target rather than just the header and lib directories. Mainly other library dependencies and possible bin locations.
- again I believe keeping hunter and os packages independent is more of importance than fallback handling.

honestly in the short period of time I have had working with hunter I really dont see a reason for having hunter turned off in a general project. However if you are building a library like say like Eigen that is where I think the option makes the most sense as lots of people will not want to use hunter just to use your library.

**Comment by NeroBurner** [comment]
It's a good idea to keep the os and hunter packages separate, but it is (IMHO) a bad idea to have hunter specific find syntaxes if not necessary. All distributions I checked (Ubuntu 14.04, Ubuntu 16.04, Debian Jessie, Debian Sid, Arch Linux, Fedora 25) have a `FindEigen3.cmake` file. In my opinion it is much easier to 'sell' Hunter if you only have to add a `hunter_add_package` call to get a specific package.
For the developer Hunter is a very nice tool to create a project. If a package maintainer comes and wants to make a package from your project he certainly wants to disable Hunter and have the distribution care for dependencies.

Even when changing Hunters find package to `Eigen3` the system and hunter package are kept separate. Just a different `FindEigen3.cmake` file will be used. I did not suggest to add a fallback to the system installed library.

In this case it was necessary to create a new `Find*.cmake` file, because Eigen3 did not provide one in its default installation. But this did recently change. Someone at Eigen-Upstream thought it is a great idea to ship a `FindEigen3.cmake` file.

Eigen 3.3.0 starts to ship a `FindEigen3.cmake` file with the default install (`make install`). It is non-relocatable and has no imported target. With Eigen 3.3.1 the delivered `FindEigen3.cmake` is relocatable AND defines a target `Eigen3::eigen`.

I suggest to update Hunter-Eigen to version 3.3.1 and slowly phase out the custom `cmake/${HUNTER_ROOT}/cmake/find/FindEigen.cmake` file.

**Comment by ruslo** [comment]
> supply the Upstream Eigen package with a FindEigen3.cmake file, which is installed just like the eigen3.pc file

This approach is correct and will work nice with system and Hunter. However file should be called `EigenConfig.cmake` and generated automatically by CMake.

**Comment by NeroBurner** [comment]
> This approach is correct and will work nice with system and Hunter. However file should be called EigenConfig.cmake and generated automatically by CMake.

I just checked again, with Eigen 3.3.1 the file is generated by CMake, but it is called `Eigen3Config.cmake`. After `make install` the install folder contains the `include` dir and tthe `share` dir. The `share` dir has the following files

```
$ ls -R share/
share/:
eigen3  pkgconfig

share/eigen3:
cmake

share/eigen3/cmake:
Eigen3Config.cmake  Eigen3ConfigVersion.cmake  Eigen3Targets.cmake  UseEigen3.cmake

share/pkgconfig:
eigen3.pc
```

**Comment by ruslo** [comment]
Okay, looks good. Then `FindEigen` should be removed and wiki page updated:
* https://github.com/ruslo/hunter/wiki/pkg.eigen

**Comment by NeroBurner** [comment]
`FindEigen` is still needed for people using older eigen packages (< 3.3.1) still provided by hunter. How do we deal with those? Shall we backport the cmake changes? Shall we remove links to old eigen downloads? Or something completely different?

I agree with updating the wiki, I'll send a pull request tomorrow

**Comment by ruslo** [comment]
> How do we deal with those?

Remove old "bad" versions and keep only good. In wiki page we can save the last Hunter version with old interface.

**Comment by ruslo** [comment]
Closing inactive discussion.
