### ISSUE TITLE
Log output doesn't use project name

### ISSUE THREAD

**Issue by alamaison** [ruslo/hunter#66]
The recent to Hunter changed the log output so that, instead of referring to the package being built, it keeps referring to 'X'.
```
Scanning dependencies of target X
make[5]: Leaving directory `/home/ubuntu/workspace/hunter/PROJECT/Washer/TOOLCHAIN/analyze/_testing/Hunter/_Base/45a4cc0/b73bf9c/6389a53/Build/Boost/filesystem/Build'
make[5]: Entering directory `/home/ubuntu/workspace/hunter/PROJECT/Washer/TOOLCHAIN/analyze/_testing/Hunter/_Base/45a4cc0/b73bf9c/6389a53/Build/Boost/filesystem/Build'
[ 12%] Creating directories for 'X'
[ 25%] Performing download step (download, verify and extract) for 'X'
-- verifying file...
     file='/home/ubuntu/workspace/hunter/PROJECT/Washer/TOOLCHAIN/analyze/_testing/Hunter/_Base/Download/Boost/1.57.0/9305649/v1.57.0.tar.gz'
-- verifying file... done
-- extracting...
     src='/home/ubuntu/workspace/hunter/PROJECT/Washer/TOOLCHAIN/analyze/_testing/Hunter/_Base/Download/Boost/1.57.0/9305649/v1.57.0.tar.gz'
     dst='/home/ubuntu/workspace/hunter/PROJECT/Washer/TOOLCHAIN/analyze/_testing/Hunter/_Base/45a4cc0/b73bf9c/6389a53/Build/Boost/filesystem/Source'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 37%] No patch step for 'X'
[ 50%] No update step for 'X'
[ 62%] Performing configure step for 'X'
```
Was this intentional?  Shouldn't 'X' here be 'Boost'?

**Comment by ruslo** [comment]
`X` is just a name of external project in build scheme ([example](https://github.com/ruslo/hunter/blob/e96ac20dabdec88affdb5458122eb95a37107d86/cmake/schemes/url_sha1_combined_release_debug.cmake.in#L37)):
```cmake
ExternalProject_Add(
    X
    URL
    @HUNTER_PACKAGE_URL@
    URL_HASH
    SHA1=@HUNTER_PACKAGE_SHA1@
```
This change applied since new layout because some internal stuff became more simplier and I've optimized away `HUNTER_PACKAGE_BASENAME` variable. To see what's really building you can find some log messages like this:
```
-- [hunter] Building Boost
...
-- [hunter] Building Boost (component: filesystem)
```

Probably `X` is not the best choice :) I'm just lazy about inventing more appropriate name. What about `EP`?

**Comment by alamaison** [comment]
Is there any way to turn `@HUNTER_PACKAGE_URL@` into a string to use as a
name.  If not, I would favour something like "HunterExternalProject" rather
than "EP".  It's best to avoid user confusion where possible.

Alex

**Comment by ruslo** [comment]
Fixed. See [v0.8.8](https://github.com/ruslo/hunter/releases/tag/v0.8.8)
