### ISSUE TITLE
Error: MySQL-client package when building on OSX. RPATH-related. 

### ISSUE THREAD

**Issue by madmongo1** [ruslo/hunter#705]
steps to reproduce:

build simple exe on OSX that uses find_package(MySQL-client)
add_executable(foo main.cpp)
target_link_libraries(foo MySQL::client)
all will build and link correctly, when you run the executable, the RPATH of libmysql.dylib points into the hunter Build directory, not the Install directory.

I suspect that the MySql cmake script is broken.

**Comment by ruslo** [comment]
According to the [hunter.cmake](https://github.com/ruslo/hunter/blob/master/cmake/projects/MySQL-client/hunter.cmake) file we are using official version and standard CMake build. So I guess it's upstream problem. They should use `@rpath` with relative path instead of full path.

Do you set shared build yourself or it's default? Static build should work I guess, can be used as a workaround. Another workaround is to remove `hunter_cacheable`, but in this case package will trigger build from sources on every URL/SHA1 update of HunterGate.

@pretyman any comments?

**Comment by pretyman** [comment]
Been a while since I last used this package, I could have been using it without `hunter_cacheable`, because I'm fine without it, and I don't recall having `@rpath` problems.

Commenting `hunter_cacheable` as @ruslo would be the easiest work around.

**Comment by ruslo** [comment]
> I could have been using it without hunter_cacheable

https://github.com/ruslo/hunter/commit/11e2da50e9672c99f6731830935a172e693fe8be

> Commenting hunter_cacheable as @ruslo would be the easiest work around.

Ok, I'll try it.

**Comment by ruslo** [comment]
@madmongo1 try this release https://github.com/ruslo/hunter/releases/tag/v0.18.19

**Comment by madmongo1** [comment]
Thant’s fixed it - thank you.

**Comment by ruslo** [comment]
Ok, closing
