### ISSUE TITLE
How does hunter handle shared libraries and establishing RPATH for 3rdparty libraries?

### ISSUE THREAD

**Issue by akalsi87** [ruslo/hunter#706]
Typically in an application with shared libraries, one would want that the RPATH to be set for all the libraries used in the third-party libraries appropriately.

So,
```
# project/CMakeLists.txt
# lots of setup code
hunter_add_package(CURL)

set(BUILD_SHARED_LIBS 1)

add_library(${sources})

target_link_libraries(project CURL::libcurl)

install(...)

# copy 3rdparty folders to install dir
# copy licenses
```

For this simple workflow to work, one would need Hunter to be able to set a relative RPATH on most non-Windows platforms.

Is this something under current consideration?

**Comment by ruslo** [comment]
RPATH can be handled in CMake code, depending on your needs:
* https://cmake.org/Wiki/CMake_RPATH_handling

Nothing to do with Hunter features as far as I understand.

**Comment by akalsi87** [comment]
Well, it does matter if you want a relocatable install folder, that the 3rdparty libraries used are also relocatable, i.e. have a relative RPATH.

For eg. libfoo depends on libcurl and libcrypto
libcurl depends on libcrypto
To safely relocate libfoo, libcurl must find libcrypto in its RPATH. So both packages must have an RPATH relative to hunter install location

**Comment by ruslo** [comment]
> must have an RPATH relative to hunter install location

Yes, it's possible and just like I said can be set in CMake code of package: `@rpath/../lib` or something. It's not a Hunter feature.

**Comment by akalsi87** [comment]
Can there be a HUNTER_USE_RPATH variable that is respected by all packages?

**Comment by ruslo** [comment]
> Can there be a HUNTER_USE_RPATH variable that is respected by all packages?

What functionality will have this variable?

**Comment by akalsi87** [comment]
If set to 1 then shared libraries will have a relative RPATH=$ORIGIN/../lib on Linux, @loader_path/../lib on Mac OS etc. for libcrypto and libcurl such that the hunter install folder can be simply copied to install location for libfoo in the libfoo example above.

So, in libfoo installation:

```
+ install
 -- + lib
 ------ libfoo.so
 ------ libcurl.so      # finds libcrypto through relative path
 ------ libcrypto.so
```

**Comment by ruslo** [comment]
> If set to 1 then shared libraries will have a relative RPATH=$ORIGIN/../lib on Linux, @loader_path/../lib on Mac OS etc.

How we can implement this? And what if package itself use another RPATH? I don't see the point of doing anything about it in Hunter, it can be easily achieved in package's CMake code.

> ------ libcurl.so      # finds libcrypto through relative path

If it's not so, then it means CURL CMake code should be fixed.

**Comment by akalsi87** [comment]
> How we can implement this? And what if package itself use another RPATH? I don't see the point of doing anything about it in Hunter, it can be easily achieved in package's CMake code.

There are standard ways to do this using CMake like you mentioned in your previous links. The problem is that it requires multiple lines of CMake code so the variable would enable setting RPATH on install.

> If it's not so, then it means CURL CMake code should be fixed.

Well, today, without adding RPATH code, libcurl will use absolute paths to libcrypto.

**Comment by ruslo** [comment]
@akalsi87 I understand your point, something is not working properly and it brokes your stuff. However I don't see any valid arguments for doing anything with Hunter. I see the problem with CURL, it means somebody have to fix CURL's CMake code. If you want to introduce any new Hunter features, then please describe functionality and implementation details, then open pull request. Thanks.

**Comment by ruslo** [comment]
Issue should be solved in CURL, closing.

**Comment by acasadom** [comment]
Hello
I know this issue has been close long time ago, because it is supposed to be out of the scope of Hunter,
Ok, I dont have a lot of experience with cmake, so sorry if the question is really simple and stupid.

I am doing a really simple example, using hunter to deal with boost dependencies, an make a hello world executable that use boost.
The little detail is that I want boost to be used as a shared library, so I have add a LOCAL config:
......................
hunter_config(
    Boost VERSION 1.58.0-p1 // I want this specific version
    CMAKE_ARGS
    BUILD_SHARED_LIBS=ON
)
......................
CMakeLists.txt
......................

cmake_minimum_required(VERSION 3.2)
set(CMAKE_CXX_STANDARD 14)

include("cmake/HunterGate.cmake")
HunterGate(
    URL "http://10.6.20.69/acme/hunter/-/archive/master/hunter-master.tar.gz"
    SHA1 "f77c84d09a1561c3ba867df9e1a7d1c757dcc645"
    LOCAL
)

project(Foo)

hunter_add_package(Boost COMPONENTS regex system filesystem)
find_package(Boost CONFIG REQUIRED regex system filesystem)

add_executable(foo foo.cpp)
target_link_libraries(
    foo 
    PUBLIC 
        Boost::regex Boost::system Boost::filesystem
)
......................

everything works fine, hunter download/build and install boost (regex/system/filesystem) and foo
project compiles

usr/bin/c++  -O3 -DNDEBUG  -rdynamic CMakeFiles/foo.dir/foo.cpp.o  -o foo /root/.hunter/_Base/f77c84d/e1266bb/cc2d780/Install/lib/libboost_regex-mt.so /root/.hunter/_Base/f77c84d/e1266bb/cc2d780/Install/lib/libboost_system-mt.so /root/.hunter/_Base/f77c84d/e1266bb/cc2d780/Install/lib/libboost_filesystem-mt.so 


But is it not running because it cannot find the shared libraries.
./foo 
./foo: error while loading shared libraries: libboost_regex-mt.so.1.58.0: cannot open shared object file: No such file or directory

My understanding reading this issue is that is cmake responsability set the rpath for foo target to allow the liker looks in the proper directory.
   Am I right? if so, the only way of getting this path is asking hunter where it has install these libraries or get the path from Boost::<componet> targets specific properties.
Am I right?
If so, how can I do that for set it as an rpath for foo target?
if not, what alternative do I have to use?

Thank you in advance.

**Comment by acasadom** [comment]
Hello

OK, I asked too quickly.. 

reading the output we can see:
-- [hunter] BOOST_ROOT: /root/.hunter/_Base/f77c84d/e1266bb/cc2d780/Install (ver.: 1.58.0-p1)
so we can use ${BOOST_ROOT}/lib for rpath

...
