### ISSUE TITLE
HUNTER_BUILD_SHARED_LIBS

### ISSUE THREAD

**Issue by akalsi87** [ruslo/hunter#707]
I would like to discuss whether it makes sense to enabling the propagation of BUILD_SHARED_LIBS and CMAKE_POSITION_INDEPENDENT_CODE globally for all hunter projects.

It makes it easier to use for a user as it is NOT typical to build a shared libraries by adding whole static archives. That is not the common case, so that is probably a default we can change.

**Comment by ruslo** [comment]
> CMAKE_POSITION_INDEPENDENT_CODE globally

See https://github.com/ruslo/hunter/issues/64

> enabling the propagation of BUILD_SHARED_LIBS ... globally

Hm... I think I've closed one by mistake https://github.com/ruslo/hunter/issues/21

I will rename this issue.

Related discussion:
* https://github.com/ruslo/hunter/issues/63

**Comment by akalsi87** [comment]
Can HUNTER_BUILD_SHARED_LIBS use BUILD_SHARED_LIBS as the default value if unspecified?

**Comment by ruslo** [comment]
> Can HUNTER_BUILD_SHARED_LIBS use BUILD_SHARED_LIBS as the default value if unspecified?

I guess it make sense.

**Comment by chfast** [comment]
cc @chfast.

**Comment by ruslo** [comment]
> Can HUNTER_BUILD_SHARED_LIBS use BUILD_SHARED_LIBS as the default value if unspecified?

On second thought it's a valid case when all 3rd parties are static and local project use `BUILD_SHARED_LIBS=ON` so I'm leaving this untouched.

Fixed:
* https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-build-shared-libs

Available since:
* https://github.com/ruslo/hunter/releases/tag/v0.19.115
