### ISSUE TITLE
Add GMock

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#76]
* https://code.google.com/p/googlemock/

**Comment by Knitschi** [comment]
I included GMock in my [fork](https://github.com/Knitschi/hunter/releases/tag/0.12.33-GoogleTest) of hunter. I did it by creating my own release of the current [googletest](https://github.com/google/googletest) version. Unlike the 1.7.0 release the repository now contains GTest and GMock and a CMakeLists file that creates both projects. This makes integration with Hunter pretty straight forward. 

I also added this [FindGMock](https://github.com/triglav/cmake-findgmock) to support find_package(GMock). Integrating this into the official Hunter release should not be too much work.

**Comment by ruslo** [comment]
Thanks for working on this!

> Unlike the 1.7.0 release the repository now contains GTest and GMock

*offtopic* I don't understand that move by GTest developers... Very strange, now git history of my fork is broken */offtopic*

> I also added this FindGMock to support find_package(GMock)

It will be much easier to generate that file automatically, see:
* https://github.com/ruslo/hunter/wiki/usr.adding.new.package#important
* https://github.com/ruslo/hunter/wiki/example.find_package.config

And it will produce much correct file. E.g. `FindGMock` will not work if debug library has prefix `-Debug` and not `d`. Also non-standard variant like `RelWithDebInfo` and `MinSizeRel` will not be found. + More and more issues.

If you'll apply this approach it would be awesome. Anyway feel free to send pull request.

**Comment by Knitschi** [comment]
I will take a look at this and see if i can come up with something that is worth a pull request.

**Comment by Knitschi** [comment]
I now created a new [hunter](https://github.com/Knitschi/hunter/releases/tag/v0.12.33-GoogleTest.2-pr) release with a new version of [GoogleTest](https://github.com/Knitschi/googletest/releases/tag/1.8.0-pr-hunter-2) to which I added the cmake code that adds config file package support. But there are still a few issues for which I am not sure if they need to be fixed.

* GTest and GMock each have an CMakeLists file. Both files now contain the same cmake package code which I more or less copied from your [example](https://github.com/forexample/package-example). This smells a little like code duplication. Maybe one could place the stuff in the parents CMakeLists file but I am not sure if this is the right way to do it.

* The cmake variables gtest_INCLUDE_DIRS and gtest_LIBRARIES are not set after calling find package. I am not sure if they should be set if one does everything right. The include directories are however set correctly.

* I am a newbe to git and github so I don't know how I can create a pull request for a complete new package in the [hunter-packages](https://github.com/hunter-packages?page=3) repositories.

* My solution is not thoroughly tested because I don't know what to test and how to test on other platforms.

If you give me some advice I can create a pull request for the googletest package and my hunter fork.

**Comment by ruslo** [comment]
> I now created a new hunter release with a new version of GoogleTest to which I added the cmake code that adds config file package support

Thanks. Okay, let's do it as we usually manage forks:
* I've created new repository: https://github.com/hunter-packages/googletest
* I've sent you invitation - after accepting you will be able to push and create releases
* branch `master` will be "clean" version, so we can do "forward merge" without conflicts with upstream
* branch `hunter` is for our experimenting (it's default)
* you can push directly to `hunter` branch but prefer creating pull request so I or somebody else can do review of the change
* create releases in a form `vX.Y.Z-hunter-pN` where `X.Y.Z` is the official version and `N` is the patch number (also I usually do just `vX.Y.Z-pN`)

> Both files now contain the same cmake package code which I more or less copied from your example. This smells a little like code duplication

Yes, this code looks the same for all projects and can be orginized into some helper function in future. I was thinking about more improvements too. For now it can be kept like that I think.

> The cmake variables gtest_INCLUDE_DIRS and gtest_LIBRARIES are not set after calling find package

You don't need them. Usually this variables set by `FindGTest` and since we are using `GTestConfig` there will be no such variables.

> I am a newbe to git and github so I don't know how I can create a pull request for a complete new package in the hunter-packages repositories

See above. tl;dr you can't :) I need to create repository first

> My solution is not thoroughly tested because I don't know what to test and how to test on other platforms.

You need to create example (like [this one](https://github.com/ruslo/hunter/tree/master/examples/GTest)) and just generate/build it. See this [wiki page](https://github.com/ruslo/hunter/wiki/dev.hunter.root) about using `jenkins.py` which will allow you to run experimental code without affecting main root directory.

**Comment by Knitschi** [comment]
I created a pull request for my changes in the googletest project. I did not get an invitation to get the rights to create releases for the googletest package. So you have to invite me again or create an release yourself.
When there is an release for the googletest package I will send an pull request for the changes to the hunter repository.

**Comment by ruslo** [comment]
> I created a pull request for my changes in the googletest project

Thanks, will take a look

>  I did not get an invitation to get the rights to create releases for the googletest package. So you have to invite me again or create an release yourself.

I see you in the team actually, can you check again?

**Comment by Knitschi** [comment]
Yes I am in. I did not know that I get the invitation via email. I joined yesterday.

**Comment by ruslo** [comment]
Fixed by https://github.com/ruslo/hunter/pull/306.

@Knitschi There is no example to test (like examples/GMock) feel free to add
