### ISSUE TITLE
OpenCL: does not build on macOS

### ISSUE THREAD

**Issue by chfast** [ruslo/hunter#772]
The OpenCL ICD loader (https://github.com/hunter-packages/OpenCL-ICD-Loader/tree/hunter) referenced by hunter us OpenCL does not build on macOS / XCode 8.3: https://travis-ci.org/ethereum-mining/ethminer/jobs/224937739.

**Comment by ruslo** [comment]
Currently OSX excluded from CI testing:
* https://github.com/ingenue/hunter/blob/51f787703afd47549d3cfea5d87f79d88947698d/.travis.yml#L58

somebody have to fix it.

**Comment by xsacha** [comment]
The comments in the OpenCL ICD loader suggest it doesn't work because OpenCL version is too old (1.2 instead of 2.x).

To use the inbuilt OpenCL (1.2), you can do find_package(OpenCL REQUIRED) without adding hunter_add_package.

**Comment by ruslo** [comment]
> Do you need ICD loader to load a vendor implementation of OpenCL (AMD/Nvidia/Intel)? If so, which vendor?

If you asking me - I have no idea, do whatever you think is appropriate. The only general note is that depending on Xcode development files is fine since both generator (`-GXcode`) and compiler version saved in toolchain-id. Depending on environment **is not**: if result of `find_package(OpenCL)` is different for machines with different GPU (AMD/Nvidia/Intel). In this case we have to improve toolchain-id calculation.

**Comment by ruslo** [comment]
Closing inactive discussion.
