### ISSUE TITLE
Teach OpenCV to find imported dependencies (patch OpenCVConfig.cmake)

### ISSUE THREAD

**Issue by alamaison** [ruslo/hunter#81]
The OpenCV example is still failing on Linux:
```
[100%] Completed 'OpenCV-debug'
[100%] Built target OpenCV-debug
-- [hunter] Build step successful (dir: /home/ubuntu/workspace/hunter/PROJECT/OpenCV/TOOLCHAIN/default/_testing/Hunter/_Base/3d795fe/015448b/d580c2e/Build/OpenCV)
-- Configuring done
CMake Error at CMakeLists.txt:16 (add_executable):
  Target "foo" links to target "TIFF::libtiff" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
```
It looks like the OpenCV config file exports the dependency on libtiff (as it should) but doesn't call find_package(TIFF ...) to resolve that dependency.  I havn't verified this but, from experience, that's what the error usually indicates.

**Comment by alamaison** [comment]
Is the OpenCV package config file custom to Hunter's version of OpenCV or part of the upstream project?

**Comment by ruslo** [comment]
>  I havn't verified this but, from experience, that's what the error usually indicates

As far as I understand there must be a command `find_package(TIFF CONFIG)` in OpenCVConfig.cmake file. So when you load `find_package(OpenCV)` then `find_package(TIFF CONFIG)` loaded automatically. I think usually TIFF built from source in OpenCV so it's not a problem. Right way is to patch OpenCV of course, but it's not trivial I think, since there is a control option WITH_TIFF. I will try to ask a question in CMake list may be I'm missing something. Currently you can use workaround:
```cmake
find_package(TIFF CONFIG)
find_package(OpenCV)
```
See [documentation](https://github.com/ruslo/hunter/wiki/pkg.opencv)

**Comment by ruslo** [comment]
> Is the OpenCV package config file custom to Hunter's version of OpenCV or part of the upstream project

upstream, I haven't change it

**Comment by ruslo** [comment]
> I will try to ask a question in CMake list 

http://public.kitware.com/pipermail/cmake-developers/2015-April/025034.html

1. is good but messy solution
2. is a quick workaround

**Comment by ruslo** [comment]
Fixed: https://github.com/hunter-packages/opencv/commit/56379cc6a702bd9d6dd8a2d8ef8fd1cba692027b

Hunter version: https://github.com/ruslo/hunter/releases/tag/v0.10.5
