### ISSUE TITLE
OpenSSL with bitcode iOS

### ISSUE THREAD

**Issue by ikliashchou** [ruslo/hunter#819]
Hi,

Was trying to use OpenSSL package with latest hunter v0.18.66 with polly toolchain iOS-10-3.cmake.

`hunter_add_package(OpenSSL)
find_package(OpenSSL REQUIRED)`

Have patched os/iphone.cmake:

`set(CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE YES)`

After clean download and build still get the linker error:

`ld: '/Users/user/HUNTER_ROOT/_Base/26028d2/d2a5da9/5db8c87/install/lib/libcrypto.a(evp_lib.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64`

The patch above helped to have OpenCV build and linked correctly, but for some reason doesn't help for OpenSSL.

Also to mention, no effect on setting `set(IOS_DEPLOYMENT_SDK_VERSION 8.0)` in toolchain for OpenSSL, while for OpenCV this worked correctly.

Any hints?

Thanks!

**Comment by ruslo** [comment]
> but for some reason doesn't help for OpenSSL

Because OpenSSL is not using CMake as a build system, hence all such variables should be detected in build scheme and corresponding compiler flags should be added explicitly. See:
* https://github.com/ruslo/hunter/blob/5a6d6b2a266a098902c83cb0ea8f42a2aa2f3c3a/cmake/modules/hunter_dump_cmake_flags.cmake

Note that currently OpenSSL + iOS scheme is not using this function, should be fixed separately:
* https://github.com/ruslo/hunter/blob/5a6d6b2a266a098902c83cb0ea8f42a2aa2f3c3a/cmake/projects/OpenSSL/schemes/url_sha1_openssl_ios.cmake.in

> set(IOS_DEPLOYMENT_SDK_VERSION 8.0) in toolchain for OpenSSL

The reason and fix is the same as for `CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE`.

**Comment by ikliashchou** [comment]
You mean I need `include(hunter_dump_cmake_flags)` in `/OpenSSL/schemes/url_sha1_openssl_ios.cmake.in`?

**Comment by ruslo** [comment]
Not just include but also call `hunter_dump_cmake_flags` and add resulting C compiler flags to the OpenSSL build. Also I don't see where `hunter_dump_cmake_flags` is working with `CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE`/`IOS_DEPLOYMENT_SDK_VERSION`, should be fixed too.

**Comment by ikliashchou** [comment]
[Implemented](https://github.com/ruslo/hunter/pull/826)
