### ISSUE TITLE
Assimp fails to build with ASSIMP_ENABLE_BOOST_WORKAROUND=ON

### ISSUE THREAD

**Issue by lukegravitt** [ruslo/hunter#849]
[Running on OSX]

Failed in two places:

First, when trying to target_link_library in code/CMakeLists.txt.
I added a check there locally, but it still fails after compilation with this error:

CMake Error at [snip]/cmake/Assimp/AssimpConfig.cmake:28 (find_package):
  Could not find a package configuration file provided by "Boost" with any of
  the following names:

    BoostConfig.cmake
    boost-config.cmake

  Add the installation prefix of "Boost" to CMAKE_PREFIX_PATH or set
  "Boost_DIR" to a directory containing one of the above files.  If "Boost"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:152 (find_package)

Removing the line `find_package(Boost CONFIG REQUIRED)` from cmake/Config.cmake.in worked for this issue, but it did not work for me when adding an IF statement.

**Comment by ruslo** [comment]
Since I see no problems with default arguments (see [pkg.assimp](https://travis-ci.org/ingenue/hunter/builds/139905456)) I can guess that the problem is in Assimp package itself. I guess `ASSIMP_ENABLE_BOOST_WORKAROUND=ON` trigger usage of Boost but `hunter_add_package(Boost)` is missing.

* [Fork](https://github.com/hunter-packages/assimp)
* [Docs](https://docs.hunter.sh/en/latest/creating-new/cmake-dependencies.html)

**Comment by ruslo** [comment]
Closing inactive discussion.
