### ISSUE TITLE
Cache upload script: mark uploaded as "from.server"

### ISSUE THREAD

**Issue by chfast** [ruslo/hunter#916]

**Comment by ruslo** [comment]
Fixed by https://github.com/ruslo/hunter/commit/b0d6cfcc8ffe769ed83a20ee868be9aa5594a623.

It was a part of the bigger change. Upload script is now called inside Hunter:
* https://docs.hunter.sh/en/latest/user-guides/hunter-user/github-cache-server.html

Available since https://github.com/ruslo/hunter/releases/tag/v0.20.0
