### ISSUE TITLE
Add OpenCV 3.3.0 iOS

### ISSUE THREAD

**Issue by ikliashchou** [ruslo/hunter#935]
3.3.0 was released recently. As I see OpenCV packages are usually "hunterized". Do you plan to add this new version?
https://github.com/opencv/opencv/releases/tag/3.3.0

**Comment by ruslo** [comment]
I've created branch `hunter-3.3.0`:
* https://github.com/hunter-packages/opencv/tree/hunter-3.3.0

Feel free to send pull request with hunterization patches from `hunter-3.2.0` branch.

**Comment by xsacha** [comment]
Missing iOS support, if someone wants to add it.

I had the same issue with Android locally when using ENABLE_NEON=ON and solved it by changing to CV_BASELINE... so that compatibility layer of changing old args to new args may be related but I have not had time to test this yet.

**Comment by ruslo** [comment]
OpenCV 3.3.0 released here:
* https://github.com/ruslo/hunter/pull/954

changing label.

**Comment by xsacha** [comment]
Works with ENABLE_NEON=OFF BUILD_WEBP=ON for anyone who sees this issue.

**Comment by ikliashchou** [comment]
But this will switch off optimization, correct?

**Comment by xsacha** [comment]
No, it will detect neon and use it.

**Comment by ruslo** [comment]
> Works with ENABLE_NEON=OFF BUILD_WEBP=ON for anyone who sees this issue.

@xsacha Can you add them to https://github.com/ruslo/hunter/pull/986?

> But this will switch off optimization, correct?

You can always add `ENABLE_NEON=ON` by custom CMAKE_ARGS:
* https://github.com/ruslo/hunter/wiki/example.custom.config.id#custom-cmake-options

**Comment by xsacha** [comment]
Since #986 was merged, this is fixed.

Note: You don't want to use ENABLE_NEON because it will break in the same way. Just let it auto-detect the __ARM_NEON from preprocessor. It will still use NEON.
Upstream just broke the way they test neon when you use ENABLE_NEON.

**Comment by ruslo** [comment]
> Since #986 was merged, this is fixed

**Comment by jdonald** [comment]
We've been debugging this for a few days now and got several levels deep into why `ENABLE_NEON=ON` is failing. A writeup on another one of its failure modes can be found in hunter-packages/opencv#28

> Just let it auto-detect the __ARM_NEON from preprocessor. It will still use NEON.

There is OpenCV code that checks `__ARM_NEON` and sets the CV_NEON macro, but the auto-detected CPU_BASELINE code is what sets `CV_CPU_CALL_NEON` and some other NEON-related macros. So when the CPU baseline is not properly detected you end up with NEON used in some places but not others throughout OpenCV.

> Note: You don't want to use ENABLE_NEON because it will break in the same way.

I think there's a problem with intentionally omitting `ENABLE_NEON=ON` / `CPU_BASELINE_FLAGS=NEON`. It means NEON detection can fail silently (due to the issue we linked or any yet unknown issues) and you'll only find out later when your code is running slower than expected.
