### ISSUE TITLE
questions about `disabled-mode`

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#955]
I've got a few questions and assumptions about `disabled-mode`

- the disabled-modules are in the project using hunter `cmake/Hunter/disabled-mode`
- the disabled-modules are `FooConfig.cmake` or `foo-config.cmake` files
- could a set of default disabled-modules be added to hunter, or is this not possible because the hunter package is not downloaded, only `HunterGate` is present
- would you recommend to use a git submodule of https://github.com/hunter-packages/disabled-mode or should only the files be copied and the repo is just a reference?
- how are `-Dfoo_DIR=<path>` variables handled?
- how hard would it be to add a `Eigen3Config.cmake` file to work on Ubuntu 14.04 (`/usr/share/cmake-2.8/Modules/FindEigen3.cmake` and 16.04 (`/usr/lib/cmake/eigen3/Eigen3Config.cmake`)

**Comment by ruslo** [comment]
> the disabled-modules are in the project using hunter cmake/Hunter/disabled-mode

Yes

> the disabled-modules are FooConfig.cmake or foo-config.cmake files

At this moment yes, but I guess it can be `FindFoo.cmake` too.

> could a set of default disabled-modules be added to hunter, or is this not possible because the hunter package is not downloaded, only HunterGate is present

Yes, I think if `HUNTER_ENABLED=OFF` then we should not touch `~/.hunter` or do any downloads. That's the point of `HUNTER_ENABLED=OFF`.

> would you recommend to use a git submodule of https://github.com/hunter-packages/disabled-mode or should only the files be copied and the repo is just a reference?

Up to you. Git submodules is easier to update but they are not part of GitHub release.

> how are -Dfoo_DIR=<path> variables handled?

Don't have any special hooks. `cmake/Hunter/disabled-mode` added to CMAKE_PREFIX_PATH. If `foo_DIR` take a priority over CMAKE_PREFIX_PATH then `find_package(foo CONFIG)` will load module from `foo_DIR` instead of `CMAKE_PREFIX_PATH`.

> how hard would it be to add a Eigen3Config.cmake file to work on Ubuntu 14.04 (/usr/share/cmake-2.8/Modules/FindEigen3.cmake and 16.04 (/usr/lib/cmake/eigen3/Eigen3Config.cmake)

Since there is no standard FindEigen3 module I think it make sense to write Eigen3Config from scratch with all functionality you need.
