### ISSUE TITLE
HUNTER_JOBS_NUMBER question

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#973]
In the documentation the variable `HUNTER_JOBS_NUMBER` is explained as follows:

```
HUNTER_JOBS_NUMBER

    - Number of parallel builds that will be used in such native tools like make -jN or xcodebuild -jobs N
    - For Visual Studio flag /MP will be used
    - Set variable to 0 to disable adding any flags: HUNTER_JOBS_NUMBER=0
    - Default: NUMBER_OF_LOGICAL_CORES
```

what happens on Visual Studio if `HUNTER_JOBS_NUMBER=1`? Will the flag `/MP` be set? O do I need to specify `HUNTER_JOBS_NUMBER=0`?

**Comment by ruslo** [comment]
> Will the flag /MP be set?

No. Adding flag to toolchain will remove default flag:
* https://github.com/ruslo/hunter/issues/142#issuecomment-100467821

Since Visual Studio 12 2013 we can use `/maxcpucount`:
* https://github.com/ruslo/hunter/blob/c548f79d3be7ff3cba37dab4d78109fc640735a2/cmake/modules/hunter_jobs_number.cmake#L51-L54
* https://github.com/ruslo/hunter/blob/c548f79d3be7ff3cba37dab4d78109fc640735a2/cmake/schemes/url_sha1_cmake.cmake.in#L60

Documentation fixed:
* https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-jobs-number

**Comment by NeroBurner** [comment]
thanks :+1:
